import {
  UtensilsCrossed,
  ShoppingBag,
  Building2,
  Truck,
  Smartphone,
  MessageSquare,
  Users,
  TrendingUp,
  Zap,
  QrCode,
  Bell,
  Heart,
  Calculator,
  Headset,
  PenTool,
  Receipt,
  Share2,
  FileText,
  Clock,
  ShieldCheck,
  Star,
  BadgePercent,
  History,
  Home,
  MapPin,
  Calendar,
  DollarSign,
  Package,
  CheckCircle2,
  Send,
  UserCheck,
  Wallet,
  Briefcase,
  Layers,
  BarChart,
  Eye,
  Handshake,
  Key,
  Truck as TruckIcon,
  CreditCard,
  ClipboardCheck,
  Globe,
  Bot,
  Repeat,
  Megaphone,
  BookOpen,
  PhoneCall,
  ArrowRightLeft,
  LayoutDashboard,
  Inbox,
  Activity,
  ChartBar,
  Sparkles,
  Building,
  GitBranch,
  Pill,
  GraduationCap,
} from 'lucide-react';

export type SectorId = 'restaurant' | 'retail' | 'realestate' | 'logistics' | 'b2b' | 'pharmacy' | 'education';
export type PillarId = 'backend_office' | 'communication_client' | 'fidelisation';

export interface SchemaNode {
  id: string;
  type: 'trigger' | 'action' | 'process' | 'result';
  label: string;
  sublabel: string;
  icon: any;
  status?: 'success' | 'active' | 'pending';
  agent?: string;
  position: { x: number; y: number };
}

export interface DemoMessage {
  from: 'client' | 'agent' | 'boss';
  text: string;
  type?: 'qr' | 'buttons' | 'catalog' | 'payment' | 'order_status' | 'receipt';
  options?: string[];
  items?: {
    name: string;
    price: string;
    image: string;
    description: string;
  }[];
}

export interface Deliverable {
  id: string;
  name: string;
  description: string;
  pillar: PillarId;
  icon: any;
  tags: string[];
  effort: 'Simple' | 'Moyen' | 'Avancé';
  timeline: string;
  agent: string;
  agentAvatar: string;
  metrics: { label: string; value: string }[];
  prospectScript: DemoMessage[];
  bossScript: DemoMessage[];
}

export interface Intent {
  id: string;
  name: string;
  icon: any;
  description: string;
  agentName: string;
  agentAvatar: string;
  agentRole: string;
  impact: string;
  metrics: { label: string; value: string; trend: 'up' | 'down'; change: string }[];
  schema: SchemaNode[];
  qrData: {
    label: string;
    description: string;
    placeholderUrl: string;
  };
  valueProp: {
    title: string;
    points: string[];
    mainMetric: string;
  };
}

export interface SectorData {
  id: SectorId;
  name: string;
  icon: any;
  color: string;
  tagline: string;
  intents: Intent[];
  deliverables: Deliverable[];
}

export const PILLARS: { id: PillarId; label: string; icon: any; color: string; description: string }[] = [
  {
    id: 'backend_office',
    label: 'Backend Office',
    icon: LayoutDashboard,
    color: '#7967FF',
    description: 'Infrastructure digitale interne — gestion des opérations, des stocks, des process métier.',
  },
  {
    id: 'communication_client',
    label: 'Communication Client',
    icon: MessageSquare,
    color: '#3B82F6',
    description: 'Tous les canaux de contact avec le client — WhatsApp, email, notifications, suivi.',
  },
  {
    id: 'fidelisation',
    label: 'Fidélisation & Croissance',
    icon: Heart,
    color: '#10B981',
    description: 'Systèmes pour retenir, engager et faire revenir le client — loyalty, offres, avis.',
  },
];

export const SECTORS: SectorData[] = [
  // ─── RESTAURATION ──────────────────────────────────────────────────────────
  {
    id: 'restaurant',
    name: 'Restauration',
    icon: UtensilsCrossed,
    color: '#FF6B6B',
    tagline: 'Commandes, stock et fidélité automatisés.',
    deliverables: [
      {
        id: 'resto_pos_dashboard',
        name: 'Dashboard Commandes & CA',
        description: 'Tableau de bord temps réel : commandes en cours, chiffre d\'affaires du jour, tickets moyens, pics d\'affluence.',
        pillar: 'backend_office',
        icon: LayoutDashboard,
        tags: ['Temps réel', 'Analytics', 'Caisse'],
        effort: 'Moyen',
        timeline: '2–3 sem',
        agent: 'Lina',
        agentAvatar: '/agents/lina-3d.png',
        metrics: [{ label: 'Gain de temps', value: '-3h/jour' }, { label: 'Erreurs caisse', value: '0%' }],
        prospectScript: [
          { from: 'client', text: 'C\'est quoi vos horaires ?' },
          { from: 'agent', text: 'Bonjour ! Le **Restaurant Le Palmier** est ouvert :\n\n🕛 Lun–Sam : 11h30 – 22h00\n🕛 Dimanche : 12h00 – 21h00\n\nVoulez-vous réserver une table ?' },
          { from: 'client', text: 'Oui pour 4 personnes ce soir.' },
          { from: 'agent', text: 'Pour ce soir à quelle heure vous conviendrait-il ?' },
          { from: 'client', text: '20h.' },
          { from: 'agent', text: 'Table pour 4 réservée ce soir à **20h** ✅ Au nom de ?' },
          { from: 'client', text: 'Bella.' },
          { from: 'agent', text: 'Parfait Mme Bella ! Réservation confirmée. On vous attend à 20h 🌴' },
        ],
        bossScript: [
          { from: 'agent', text: '📊 **Rapport du soir — Restaurant Le Palmier**' },
          { from: 'agent', text: '🍽️ Couverts : **47**\n💰 CA : **128 500 FCFA** (+12% vs hier)\n🕐 Pic d\'affluence : 12h30–13h45\n🎫 Ticket moyen : **2 734 FCFA**' },
          { from: 'boss', text: 'Et les plats du jour ?' },
          { from: 'agent', text: 'Plats du jour = **68% des commandes** ce soir. Le Ndolé crevettes est le best-seller (14 portions).\n\nJe programme une alerte si le CA passe sous 80 000 FCFA ?' },
          { from: 'boss', text: 'Oui fais-le.' },
          { from: 'agent', text: 'Alerte configurée ✅ Bonne soirée !' },
        ],
      },
      {
        id: 'resto_stock_alert',
        name: 'Gestion Stock & Alertes',
        description: 'Inventaire automatisé avec alertes WhatsApp quand un ingrédient est en rupture. Suggestions de commande fournisseur.',
        pillar: 'backend_office',
        icon: Package,
        tags: ['Inventaire', 'Alertes', 'Fournisseurs'],
        effort: 'Moyen',
        timeline: '1–2 sem',
        agent: 'Lina',
        agentAvatar: '/agents/lina-3d.png',
        metrics: [{ label: 'Gaspillage', value: '-40%' }, { label: 'Ruptures', value: '0' }],
        prospectScript: [
          { from: 'client', text: 'Bonjour, vous avez encore du Ndolé pour ce soir ?' },
          { from: 'agent', text: 'Bonjour ! Oui, le Ndolé crevettes est disponible ce soir 🦐 Nous en avons encore **8 portions**. Voulez-vous réserver la vôtre ?' },
          { from: 'client', text: 'Oui, une portion pour 20h.' },
          { from: 'agent', text: 'Votre Ndolé est réservé pour **20h** ✅ À tout à l\'heure !' },
        ],
        bossScript: [
          { from: 'agent', text: '⚠️ **Alerte stock — Restaurant Le Palmier**\n\nIl reste **3 kg de poulet** au congélateur. Rupture estimée : demain midi.' },
          { from: 'boss', text: 'Je commande combien ?' },
          { from: 'agent', text: 'Basé sur les 7 derniers jours : **15 kg recommandés**.\n\nFournisseur Avicole du Centre disponible demain avant 8h. Je passe la commande ?' },
          { from: 'boss', text: 'Oui vas-y.' },
          { from: 'agent', text: 'Commande envoyée ✅ Livraison confirmée **demain 7h30**. Inventaire mis à jour automatiquement.' },
        ],
      },
      {
        id: 'resto_whatsapp_order',
        name: 'Commandes WhatsApp IA',
        description: 'Le client commande directement sur WhatsApp. L\'agent IA gère le menu, les personnalisations et le paiement Mobile Money.',
        pillar: 'communication_client',
        icon: MessageSquare,
        tags: ['WhatsApp', 'IA', 'Paiement'],
        effort: 'Avancé',
        timeline: '2–4 sem',
        agent: 'Lina',
        agentAvatar: '/agents/lina-3d.png',
        metrics: [{ label: 'Commandes auto', value: '100%' }, { label: 'Panier moyen', value: '+25%' }],
        prospectScript: [
          { from: 'client', text: 'Scanne le QR Code sur la table...', type: 'qr' },
          { from: 'agent', text: 'Bienvenue au **Restaurant Le Palmier** 🌴\n\nJe suis Lina, votre assistante digitale. Je vous aide à commander sans attendre.\n\nQue souhaitez-vous faire ?', type: 'buttons', options: ['Voir le menu', 'Commander', 'Appeler un serveur'] },
          { from: 'client', text: 'Voir le Menu 📋' },
          { from: 'agent', text: 'Voici notre sélection du jour. Appuyez sur **Voir les produits** pour choisir vos plats et boissons directement dans WhatsApp.', type: 'catalog', items: [
            { name: 'Ndolé Crevettes', price: '5 000 FCFA', image: '/dev-assets/resto-plate.png', description: 'Le classique camerounais, onctueux et riche.' },
            { name: 'Poulet DG', price: '4 500 FCFA', image: '/dev-assets/resto-plate.png', description: 'Poulet frit, plantains mûrs et petits légumes.' },
            { name: 'Jus de Bissap Glacé', price: '1 000 FCFA', image: 'https://images.unsplash.com/photo-1595981267035-7b04ca84a82d?q=80&w=200&h=200&auto=format&fit=crop', description: 'Fait maison, parfumé à la menthe.' },
            { name: 'Jus de Gingembre', price: '1 200 FCFA', image: 'https://images.unsplash.com/photo-1615485290382-441e4d0c9cb5?q=80&w=200&h=200&auto=format&fit=crop', description: 'Épicé et énergisant, 100% naturel.' },
            { name: 'Jus de Baobab (Bouye)', price: '1 500 FCFA', image: 'https://images.unsplash.com/photo-1556881286-fc6915169721?q=80&w=200&h=200&auto=format&fit=crop', description: 'Onctueux, riche en vitamine C.' },
            { name: 'Jus d\'Ananas Frais', price: '1 200 FCFA', image: 'https://images.unsplash.com/photo-1613478223719-2ab802602423?q=80&w=200&h=200&auto=format&fit=crop', description: 'Pressé à froid, sans sucre ajouté.' },
            { name: 'Eau Minérale 1.5L', price: '600 FCFA', image: 'https://images.unsplash.com/photo-1548839140-29a748635c68?q=80&w=200&h=200&auto=format&fit=crop', description: 'Fraîche.' }
          ]},
          { from: 'client', text: 'J\'ai ajouté 1 Ndolé crevettes et 1 Bissap glacé.' },
          { from: 'agent', text: 'Parfait. Voulez-vous être servi à table ou récupérer au comptoir ?', type: 'buttons', options: ['Servir à ma table', 'À emporter', 'Livraison'] },
          { from: 'client', text: 'Servir à ma table' },
          { from: 'agent', text: 'Quel est votre numéro de table ?', type: 'buttons', options: ['Table 7', 'Table 8', 'Je ne sais pas'] },
          { from: 'client', text: 'Table 7' },
          { from: 'agent', text: 'Excellent choix !\n\n**Commande #LP-1847**\n• 1x Ndolé Crevettes — 5 000 FCFA\n• 1x Jus de Bissap Glacé — 1 000 FCFA\n\nTotal : **6 000 FCFA**\nService : **Table 7**\nTemps estimé : **15 min**\n\nOn lance la préparation après paiement ?', type: 'buttons', options: ['Payer maintenant', 'Modifier le panier'] },
          { from: 'client', text: 'Payer maintenant' },
          { from: 'agent', text: 'Choisissez votre mode de paiement Mobile Money :', type: 'buttons', options: ['Orange Money', 'MTN MoMo', 'Wave'] },
          { from: 'client', text: 'Orange Money' },
          { from: 'agent', text: 'Un message de confirmation va apparaître sur votre téléphone. Entrez votre code secret pour valider les **6 000 FCFA**. ✅', type: 'payment' },
          { from: 'agent', text: 'Paiement reçu.\n\n**Reçu #OM-72841**\nCommande : #LP-1847\nMontant : **6 000 FCFA**\nStatut : payé\n\nVotre commande part en cuisine maintenant.', type: 'receipt' },
          { from: 'agent', text: '**Suivi commande #LP-1847**\n\n✅ Paiement validé\n✅ Envoyée en cuisine\n🕒 Préparation en cours\n○ Dressage\n○ Servie à table\n\nTemps restant estimé : **12 min**', type: 'order_status' },
          { from: 'agent', text: 'Petite mise à jour : votre Ndolé est presque prêt. Le serveur arrive à la **Table 7** dans environ **4 min**.' },
          { from: 'agent', text: '**Commande servie** ✅\n\nVotre Ndolé Crevettes et votre Bissap glacé viennent d\'être servis à la **Table 7**.\n\nBesoin d\'autre chose ?', type: 'buttons', options: ['Ajouter une boisson', 'Demander l\'addition', 'Tout est bon'] },
          { from: 'client', text: 'Tout est bon' },
          { from: 'client', text: 'C\'était délicieux, merci Lina !' },
          { from: 'agent', text: 'Ravi de l\'entendre ! 😊\n\nComment évalueriez-vous votre expérience au **Palmier** aujourd\'hui ?', type: 'buttons', options: ['5 étoiles - Excellent', '4 étoiles - Très bien', 'À améliorer'] },
          { from: 'client', text: '⭐⭐⭐⭐⭐ Excellent' },
          { from: 'agent', text: 'Merci beaucoup pour votre retour ! 🙏\n\nVous venez de gagner **60 points** de fidélité.\n\nAncien solde : 120 pts\nNouveau solde : **180 pts**\n\nEncore **20 points** et votre prochain dessert est offert.' },
          { from: 'agent', text: 'Souhaitez-vous recevoir votre reçu et vos points de fidélité sur WhatsApp ?', type: 'buttons', options: ['Oui, envoyer le reçu', 'Non merci'] },
          { from: 'client', text: 'Oui, envoyer le reçu' },
          { from: 'agent', text: 'C\'est fait. Reçu envoyé, points crédités et avis enregistré.\n\nMerci Fatou, à très bientôt au **Restaurant Le Palmier** 🌴' },
        ],
        bossScript: [
          { from: 'agent', text: '🔔 **Nouvelle commande — Table 7**\n\nCommande #LP-1847\n• 1x Ndolé Crevettes\n• 1x Jus de Bissap Glacé\n\nMontant : **6 000 FCFA**\nStatut : attente paiement' },
          { from: 'agent', text: '💰 **Paiement validé**\n\n6 000 FCFA reçus via Orange Money.\nReçu #OM-72841 généré.\nCommande envoyée automatiquement en cuisine.' },
          { from: 'agent', text: '👨‍🍳 **Cuisine notifiée**\n\nTable 7 · priorité normale · ETA 15 min.\nLe ticket est affiché sur l\'écran cuisine.' },
          { from: 'agent', text: '🍽️ **Commande Table 7 servie**\n\nTemps de préparation : **12 min**\nObjectif : 15 min\nPerformance : optimale ✅' },
          { from: 'agent', text: '⭐ **Nouvel avis 5/5 — Table 7**\n\n« C\'était délicieux, merci Lina ! »\n\n60 points crédités. Le reçu et le solde fidélité ont été envoyés au client.' },
          { from: 'boss', text: 'On est à combien de commandes WhatsApp ce midi ?' },
          { from: 'agent', text: 'Ce midi : **14 commandes** via WhatsApp pour un total de **82 400 FCFA**.\n\nPanier moyen : **5 885 FCFA** (+18% vs commandes comptoir).\n\nAucune erreur de saisie, Lina gère tout.' },
          { from: 'boss', text: 'Et il reste assez de Ndolé pour ce soir ?' },
          { from: 'agent', text: 'Il reste **9 portions** vendables.\n\nAu rythme actuel, rupture probable vers **20h10**. Je recommande de pousser Poulet DG dans le menu WhatsApp à partir de 19h45.' },
        ],
      },
      {
        id: 'resto_review_flow',
        name: 'Flow Avis & Réputation',
        description: 'Après chaque repas, l\'agent envoie un message WhatsApp. Avis positif → redirigé Google. Avis négatif → géré en interne.',
        pillar: 'communication_client',
        icon: Star,
        tags: ['Google Reviews', 'Reputation', 'Auto'],
        effort: 'Simple',
        timeline: '1 sem',
        agent: 'Lina',
        agentAvatar: '/agents/lina-3d.png',
        metrics: [{ label: 'Avis Google', value: '+4.8★' }, { label: 'Gestion crises', value: '100%' }],
        prospectScript: [
          { from: 'agent', text: 'Bonsoir Fatou 😊 C\'est Lina du **Restaurant Le Palmier**. J\'espère que votre repas s\'est bien passé ce soir !' },
          { from: 'agent', text: 'Comment évalueriez-vous votre expérience ?\n\n⭐⭐⭐⭐⭐ Excellent\n⭐⭐⭐⭐ Bien\n⭐⭐⭐ Moyen\n⭐⭐ À améliorer' },
          { from: 'client', text: '⭐⭐⭐⭐⭐ Excellent, le Ndolé était parfait !' },
          { from: 'agent', text: 'Merci Fatou ! 🙏 Pourriez-vous nous laisser un avis Google ?\n\n👉 g.page/lepalmier-yaounde\n\nÀ très vite !' },
        ],
        bossScript: [
          { from: 'agent', text: '⭐ **Nouvel avis reçu — Fatou N.**\n\n« Excellent, le Ndolé était parfait ! » — 5/5\n\nRedirigée vers Google pour laisser un avis public ✅' },
          { from: 'boss', text: 'Et si quelqu\'un met une mauvaise note ?' },
          { from: 'agent', text: 'Si note ≤ 3/5, je gère en interne : je m\'excuse, je propose un geste commercial et je vous alerte. **Ça n\'arrive jamais sur Google.** 🛡️' },
          { from: 'boss', text: 'Parfait.' },
          { from: 'agent', text: 'Ce mois : **34 nouveaux avis Google**, note moyenne **4.8 ★**. +0.6 points vs le mois dernier.' },
        ],
      },
      {
        id: 'resto_loyalty',
        name: 'Programme Fidélité QR',
        description: 'Chaque client scan un QR sur sa table → opt-in WhatsApp → points de fidélité automatiques → offres exclusives envoyées le midi.',
        pillar: 'fidelisation',
        icon: BadgePercent,
        tags: ['QR Code', 'Loyalty', 'WhatsApp'],
        effort: 'Moyen',
        timeline: '1–2 sem',
        agent: 'Lina',
        agentAvatar: '/agents/lina-3d.png',
        metrics: [{ label: 'Rétention', value: '+40%' }, { label: 'CA généré', value: '+850k XAF/mois' }],
        prospectScript: [
          { from: 'agent', text: 'Bienvenue au **Restaurant Le Palmier** ! 🌴\n\nJe suis Lina. En scannant ce QR, vous rejoignez notre programme fidélité et recevez **un dessert offert** dès aujourd\'hui 🎁' },
          { from: 'client', text: 'Ah sympa ! Comment je m\'inscris ?' },
          { from: 'agent', text: 'Simple : dites-moi juste votre prénom 😊' },
          { from: 'client', text: 'Éric.' },
          { from: 'agent', text: 'Bienvenue Éric ! 🎉 **50 points** crédités. Votre dessert offert vous attend — dites-le au serveur.\n\nChaque visite = points = réductions 🎁' },
          { from: 'client', text: 'Super concept !' },
          { from: 'agent', text: 'À bientôt Éric 😉' },
        ],
        bossScript: [
          { from: 'agent', text: '🎉 **Nouveau membre fidélité : Éric M.**\n\nTable 7 — inscrit via QR à 20h14\n50 points attribués, dessert offert notifié au serveur.' },
          { from: 'boss', text: 'Combien d\'inscrits ce mois ?' },
          { from: 'agent', text: '**127 nouveaux membres** ce mois 🚀\n\nTop table : Table 7 (22 scans)\nTaux d\'opt-in WhatsApp : **83%**\nCA additionnel estimé : **+320 000 FCFA**' },
          { from: 'boss', text: 'Envoie une promo aux membres qui n\'ont pas commandé cette semaine.' },
          { from: 'agent', text: 'Campagne envoyée à **41 clients inactifs** ✅\n\n« Éric, votre table préférée vous attend 🌴 -10% ce weekend avec le code RETOUR10 »' },
        ],
      },
      {
        id: 'resto_reactivation',
        name: 'Relances & Réactivation',
        description: 'Campagnes automatiques ciblées : "Vous ne nous avez pas rendu visite depuis 14 jours — voici une offre spéciale."',
        pillar: 'fidelisation',
        icon: Repeat,
        tags: ['Campagnes', 'Segmentation', 'Auto'],
        effort: 'Simple',
        timeline: '3 jours',
        agent: 'Lina',
        agentAvatar: '/agents/lina-3d.png',
        metrics: [{ label: 'Taux retour', value: '+32%' }, { label: 'Automatisation', value: '100%' }],
        prospectScript: [
          { from: 'agent', text: 'Bonjour Éric ! 👋 Ça fait 14 jours qu\'on ne vous a pas vu au **Restaurant Le Palmier**...' },
          { from: 'agent', text: 'On vous a réservé une surprise : **-15% sur votre prochain repas** valable jusqu\'à vendredi 🎁\n\nCode : RETOUR15' },
          { from: 'client', text: 'Ah trop bien ! Je passe demain midi.' },
          { from: 'agent', text: 'Super ! À demain Éric 🗓️ On vous attend !' },
        ],
        bossScript: [
          { from: 'agent', text: '📣 **Campagne de réactivation lancée**\n\n41 clients absents depuis +14j contactés automatiquement.' },
          { from: 'boss', text: 'Et les résultats ?' },
          { from: 'agent', text: '📊 **Résultats — 48h après envoi :**\n\n✅ 13 clients revenus au restaurant\n💰 CA généré : **62 400 FCFA**\n📈 Taux de retour : **32%**\n\nProchain envoi programmé dans 7 jours.' },
          { from: 'boss', text: 'Excellent.' },
          { from: 'agent', text: 'Je continue à surveiller et relancer automatiquement. Aucune action de votre part requise ✅' },
        ],
      },
    ],
    intents: [
      {
        id: 'whatsapp_order_interactive',
        name: 'Commande WhatsApp AI Interactive',
        icon: ShoppingBag,
        description: 'Parcours complet : Scan QR → Catalogue Interactif → Commande → Paiement.',
        agentName: 'Lina',
        agentAvatar: '/agents/lina-3d.png',
        agentRole: 'Sales Assistant',
        impact: '+25% de panier moyen',
        metrics: [
          { label: 'Automatisation', value: '100%', trend: 'up', change: 'Total' },
          { label: 'Gain de temps', value: '15 min', trend: 'down', change: 'Client' },
          { label: 'Conversion', value: '45%', trend: 'up', change: '+15%' },
        ],
        qrData: {
          label: 'Commander maintenant',
          description: 'Le client scanne le QR code sur sa table ou son flyer.',
          placeholderUrl: 'https://api.qrserver.com/v1/create-qr-code/?size=300x300&data=ozirus_resto_order&color=FF6B6B',
        },
        valueProp: {
          title: 'Expérience Client Premium',
          points: [
            'Plus d\'attente au comptoir ou au service',
            'Catalogue visuel et interactif directement dans WhatsApp',
            'Paiement sécurisé intégré Mobile Money',
          ],
          mainMetric: 'Zéro friction, satisfaction totale',
        },
        schema: [
          { id: 'w1', type: 'trigger', label: 'Scan QR Code', sublabel: 'Entrée dans le tunnel', icon: QrCode, position: { x: 5, y: 50 }, status: 'success' },
          { id: 'w2', type: 'process', label: 'IA Welcome', sublabel: 'Ouverture WhatsApp', icon: MessageSquare, agent: 'Lina', position: { x: 25, y: 50 }, status: 'active' },
          { id: 'w3', type: 'action', label: 'Envoi Catalogue', sublabel: 'Interactive Menu', icon: Layers, position: { x: 45, y: 30 }, status: 'success' },
          { id: 'w4', type: 'process', label: 'Panier IA', sublabel: 'Gestion commandes', icon: ShoppingBag, agent: 'Lina', position: { x: 65, y: 50 }, status: 'active' },
          { id: 'w5', type: 'action', label: 'Lien Paiement', sublabel: 'Mobile Money Pay', icon: Wallet, position: { x: 45, y: 70 }, status: 'success' },
          { id: 'w6', type: 'result', label: 'Order Confirmed', sublabel: 'Push Cuisine', icon: UtensilsCrossed, position: { x: 90, y: 50 }, status: 'success' },
        ],
      },
    ],
  },

  // ─── IMMOBILIER ────────────────────────────────────────────────────────────
  {
    id: 'realestate',
    name: 'Immobilier',
    icon: Home,
    color: '#7967FF',
    tagline: 'Vendez des biens, l\'IA s\'occupe des visites.',
    deliverables: [
      {
        id: 'immo_crm',
        name: 'CRM Prospects & Pipeline',
        description: 'Suivi de chaque prospect depuis le premier contact jusqu\'à la signature. Relances automatiques, score de solvabilité, statut du dossier.',
        pillar: 'backend_office',
        icon: GitBranch,
        tags: ['CRM', 'Pipeline', 'Score'],
        effort: 'Avancé',
        timeline: '3–4 sem',
        agent: 'Ismaël',
        agentAvatar: '/agents/ismael-3d.png',
        metrics: [{ label: 'Dossiers traités', value: 'x3' }, { label: 'Temps agent', value: '-20h/sem' }],
        prospectScript: [
          { from: 'boss', text: 'Donne-moi le pipeline du jour.' },
          { from: 'agent', text: '📊 **Pipeline Prestige Immo — 4 juin**\n\n🔴 Chaud (3) : Kamga, Ngo, Essoh\n🟡 Tiède (4) : en cours de qualification\n🔵 Froid (5) : relances auto programmées' },
          { from: 'boss', text: 'Relance M. Essoh pour son virement.' },
          { from: 'agent', text: 'Message envoyé à M. Essoh ✅ Relance auto dans 24h si pas de réponse. Je prépare son contrat en avance ?' },
          { from: 'boss', text: 'Oui.' },
          { from: 'agent', text: 'Contrat M. Essoh — Terrain Nkolbisson généré ✅ Prêt à envoyer dès validation.' },
        ],
        bossScript: [
          { from: 'agent', text: '📊 **Vue pipeline — Prestige Immo**\n\n12 prospects actifs · 3 en signature · 2 ventes ce mois' },
          { from: 'boss', text: 'Combien de cautions encaissées cette semaine ?' },
          { from: 'agent', text: '**7 cautions** encaissées cette semaine via Mobile Money.\n\nTotal : **350 000 FCFA** sécurisés.\nAucun no-show sur les visites 🎯' },
          { from: 'boss', text: 'Et les temps de traitement ?' },
          { from: 'agent', text: 'Avant Ozirus : **4,5 jours** par dossier en moyenne.\nAvec Ozirus : **1,2 jours** ✅\n\nSoit **-73%** de temps de traitement.' },
        ],
      },
      {
        id: 'immo_doc_auto',
        name: 'Génération de Documents Auto',
        description: 'Contrats, fiches de bien, compromis de vente générés automatiquement depuis les données prospect et envoyés par WhatsApp/email.',
        pillar: 'backend_office',
        icon: FileText,
        tags: ['Contrats', 'PDF Auto', 'E-sign'],
        effort: 'Moyen',
        timeline: '2 sem',
        agent: 'Ismaël',
        agentAvatar: '/agents/ismael-3d.png',
        metrics: [{ label: 'Délai dossier', value: '-2 jours' }, { label: 'Erreurs', value: '0%' }],
        prospectScript: [
          { from: 'client', text: 'Bonjour, j\'ai besoin du compromis de vente pour la Villa Bastos.' },
          { from: 'agent', text: 'Bonjour M. Kamga ! Je génère votre compromis de vente — cela prend **30 secondes** ⏱️' },
          { from: 'agent', text: '📄 **Compromis de vente — Villa Bastos**\nPrix : 85 000 000 FCFA\nDate signature : 14 juin 2025\n\nDocument envoyé sur WhatsApp ✅' },
          { from: 'client', text: 'Reçu, merci !' },
          { from: 'agent', text: 'Je vous notifie dès que les deux parties ont signé 🤝' },
        ],
        bossScript: [
          { from: 'agent', text: '📄 **Nouveau document généré**\n\nCompromis de vente — M. Kamga / Villa Bastos\nGénéré et envoyé en **28 secondes**.' },
          { from: 'boss', text: 'Combien de docs générés ce mois ?' },
          { from: 'agent', text: 'Ce mois : **34 documents** générés automatiquement.\n\n📄 12 contrats de vente\n📄 15 fiches descriptives\n📄 7 reçus de caution\n\n**0 erreur** de saisie. **0 relance** manuelle.' },
        ],
      },
      {
        id: 'immo_qualification',
        name: 'Qualification & KYC Prospect',
        description: 'L\'agent IA interviewe le prospect sur WhatsApp, collecte les pièces d\'identité et les justificatifs, filtre les curieux des acheteurs sérieux.',
        pillar: 'communication_client',
        icon: UserCheck,
        tags: ['KYC', 'WhatsApp', 'IA'],
        effort: 'Avancé',
        timeline: '2–3 sem',
        agent: 'Ismaël',
        agentAvatar: '/agents/ismael-3d.png',
        metrics: [{ label: 'Visites qualifiées', value: '100%' }, { label: 'Temps perdu', value: '0h' }],
        prospectScript: [
          { from: 'client', text: 'Bonjour, j\'ai vu votre annonce pour la villa à Bastos.' },
          { from: 'agent', text: 'Bonjour ! Je suis Ismaël, l\'assistant de **Prestige Immo** 🏡\n\nMerci de votre intérêt. Pour organiser votre visite, quel est votre budget approximatif ?' },
          { from: 'client', text: 'Entre 80 et 90 millions.' },
          { from: 'agent', text: 'Parfait, ce bien est dans votre budget. Pour réserver votre créneau, une caution remboursable de **50 000 FCFA** est requise.\n\nPaiement Mobile Money ?' },
          { from: 'client', text: 'Oui, par Orange Money.' },
          { from: 'agent', text: 'Numéro Orange Money : **677 XX XX XX**. Dès réception, je vous confirme les créneaux disponibles 📅' },
        ],
        bossScript: [
          { from: 'agent', text: '✅ **Nouveau prospect qualifié**\n\nM. Diop — Budget 80–90M FCFA\nCaution 50 000 FCFA reçue via Orange Money\nVisite planifiée : Samedi 9h' },
          { from: 'boss', text: 'Combien de curieux éliminés cette semaine ?' },
          { from: 'agent', text: 'Cette semaine : **23 contacts reçus**\n\n✅ 7 qualifiés (caution payée)\n❌ 16 éliminés (budget insuffisant ou pas sérieux)\n\nVous n\'avez géré **aucun appel inutile**.' },
        ],
      },
      {
        id: 'immo_visite_agenda',
        name: 'Planification de Visites Auto',
        description: 'Le prospect choisit un créneau dans l\'agenda de l\'agent. Rappels automatiques H-24 et H-2 avant la visite. Caution Mobile Money pré-visite.',
        pillar: 'communication_client',
        icon: Calendar,
        tags: ['Agenda', 'Rappels', 'Mobile Money'],
        effort: 'Moyen',
        timeline: '1–2 sem',
        agent: 'Ismaël',
        agentAvatar: '/agents/ismael-3d.png',
        metrics: [{ label: 'No-show', value: '0%' }, { label: 'Dépôts MM', value: '100%' }],
        prospectScript: [
          { from: 'agent', text: 'Paiement reçu ✅ Voici les créneaux disponibles :\n\n📅 Jeu 12 juin — 10h\n📅 Ven 13 juin — 14h\n📅 Sam 14 juin — 9h' },
          { from: 'client', text: 'Samedi 9h.' },
          { from: 'agent', text: 'Visite confirmée **sam 14 juin à 9h** 🗓️\n\nAgent : M. Tamba — +237 6XX XX XX\nAdresse : Rue des Frangipaniers, Bastos\n\nJe vous rappelle vendredi soir et samedi matin.' },
          { from: 'client', text: 'Merci !' },
          { from: 'agent', text: 'À samedi ! 🏡' },
        ],
        bossScript: [
          { from: 'agent', text: '📅 **Agenda de la semaine — Prestige Immo**\n\n7 visites planifiées · 7/7 cautions reçues · 0 no-show' },
          { from: 'boss', text: 'Les rappels sont partis ?' },
          { from: 'agent', text: '✅ Rappels envoyés à tous les visiteurs :\n\nVendredi 21h → « Rappel visite demain 9h »\nSamedi 7h → « Votre visite dans 2h, M. Tamba vous attend »\n\n**0 désistement** enregistré.' },
        ],
      },
      {
        id: 'immo_relance',
        name: 'Relance Prospects Froids',
        description: 'Campagnes de relance automatiques pour les prospects ayant visité mais n\'ayant pas encore signé. Suivi sur 90 jours.',
        pillar: 'fidelisation',
        icon: Repeat,
        tags: ['Relance', 'Suivi 90j', 'Auto'],
        effort: 'Simple',
        timeline: '3 jours',
        agent: 'Ismaël',
        agentAvatar: '/agents/ismael-3d.png',
        metrics: [{ label: 'Conversions récupérées', value: '+28%' }, { label: 'Accélération vente', value: '2.5 mois' }],
        prospectScript: [
          { from: 'agent', text: 'Bonjour ! Ismaël de **Prestige Immo**. Vous avez visité la Villa Bastos il y a 3 semaines. Avez-vous avancé dans votre réflexion ?' },
          { from: 'client', text: 'J\'attends juste ma banque pour le financement.' },
          { from: 'agent', text: 'Pas de souci, le bien est toujours dispo ! Si votre banque a besoin d\'une attestation de valeur, je la génère en 5 min 📄' },
          { from: 'client', text: 'Ah oui ils demandent justement ça !' },
          { from: 'agent', text: 'Je vous l\'envoie d\'ici 10 min ✅' },
        ],
        bossScript: [
          { from: 'agent', text: '📣 **Relances automatiques — cette semaine**\n\n18 prospects froids contactés (visite > 21 jours sans suite)' },
          { from: 'boss', text: 'Des conversions ?' },
          { from: 'agent', text: '✅ **5 prospects réactivés** cette semaine :\n\n3 ont repris contact pour relancer leur dossier\n2 ont signé un compromis\n\nCA récupéré : **+170M FCFA** de pipeline réactivé.' },
        ],
      },
      {
        id: 'immo_referral',
        name: 'Programme Referral Client',
        description: 'Après la vente, l\'agent envoie un message de satisfaction et propose une commission de parrainage pour chaque client référé.',
        pillar: 'fidelisation',
        icon: Share2,
        tags: ['Parrainage', 'Commission', 'Automatique'],
        effort: 'Simple',
        timeline: '1 sem',
        agent: 'Ismaël',
        agentAvatar: '/agents/ismael-3d.png',
        metrics: [{ label: 'Leads référés', value: '+35%' }, { label: 'Coût acquisition', value: '-60%' }],
        prospectScript: [
          { from: 'agent', text: 'Félicitations M. Kamga ! 🎉 Bienvenue dans votre nouvelle villa Bastos.' },
          { from: 'agent', text: 'Si vous parrainez un ami qui achète chez nous → **150 000 FCFA** de commission. Vous avez quelqu\'un en tête ?' },
          { from: 'client', text: 'Oui, mon collègue cherche quelque chose.' },
          { from: 'agent', text: 'Envoyez-lui : **prestige-immo.cm/ref/kamga**\nJe vous notifie si la vente aboutit 🤝' },
        ],
        bossScript: [
          { from: 'agent', text: '🤝 **Programme Referral — ce mois**\n\n8 clients actifs ont partagé leur lien\n3 nouveaux acheteurs référés' },
          { from: 'boss', text: 'Combien ça m\'a coûté vs une pub classique ?' },
          { from: 'agent', text: 'Coût total commissions referral : **450 000 FCFA**\nVs budget pub pour 3 leads qualifiés : ~**1 800 000 FCFA**\n\n**Économie : -75%** sur le coût d\'acquisition 🎯' },
        ],
      },
    ],
    intents: [
      {
        id: 'realestate_escrow',
        name: 'Vente & Sécurisation Mobile Money',
        icon: ShieldCheck,
        description: 'Sécurisez les réservations et qualifiez les acheteurs avec l\'IA et Mobile Money.',
        agentName: 'Ismaël',
        agentAvatar: '/agents/ismael-3d.png',
        agentRole: 'Real Estate Master',
        impact: 'Zéro désistement sur les visites',
        metrics: [
          { label: 'Visites Qualifiées', value: '100%', trend: 'up', change: 'Total' },
          { label: 'Dépôts OM/Momo', value: 'x3', trend: 'up', change: '+200%' },
          { label: 'Temps Agent', value: '-20h/sem', trend: 'up', change: 'Gagné' },
        ],
        qrData: {
          label: 'Visiter & Réserver ce bien',
          description: 'Affiche "A VENDRE" avec flow de qualification intégré.',
          placeholderUrl: 'https://api.qrserver.com/v1/create-qr-code/?size=300x300&data=ozirus_realestate_escrow&color=7967FF',
        },
        valueProp: {
          title: 'Ce que gagne le promoteur',
          points: [
            'Filtrage automatique des curieux par caution MM',
            'Envoi automatique du titre foncier et plans PDF',
            'Relance des prospects ayant visité mais pas encore signé',
          ],
          mainMetric: 'Accélération des ventes de 2.5 mois',
        },
        schema: [
          { id: 'r1', type: 'trigger', label: 'Scan Affiche Bien', sublabel: 'Intérêt immédiat', icon: Eye, position: { x: 10, y: 50 }, status: 'success' },
          { id: 'r2', type: 'process', label: 'Triage IA', sublabel: 'Ismaël vérifie le budget', icon: UserCheck, agent: 'Ismaël', position: { x: 30, y: 50 }, status: 'active' },
          { id: 'r3', type: 'action', label: 'Dépôt Garantie', sublabel: 'Sécurisation via MM', icon: Wallet, position: { x: 50, y: 20 }, status: 'success' },
          { id: 'r4', type: 'process', label: 'Planif Visite', sublabel: 'Sync Calendrier', icon: Calendar, agent: 'Ismaël', position: { x: 50, y: 80 }, status: 'active' },
          { id: 'r5', type: 'action', label: 'Remise des Clés', sublabel: 'Contrat auto généré', icon: Key, position: { x: 75, y: 50 }, status: 'success' },
          { id: 'r6', type: 'result', label: 'Vente Conclue', sublabel: 'Succès Ozirus', icon: Handshake, position: { x: 95, y: 50 }, status: 'success' },
        ],
      },
    ],
  },

  // ─── LOGISTIQUE ────────────────────────────────────────────────────────────
  {
    id: 'logistics',
    name: 'Logistique',
    icon: Truck,
    color: '#F59E0B',
    tagline: 'Le suivi de colis, sans le stress.',
    deliverables: [
      {
        id: 'log_ops_dashboard',
        name: 'Dashboard Opérations & Livreurs',
        description: 'Vue en temps réel de tous les colis en transit, positions des livreurs, statuts de livraison, et écarts de caisse.',
        pillar: 'backend_office',
        icon: LayoutDashboard,
        tags: ['Temps réel', 'Livreurs', 'Caisse'],
        effort: 'Avancé',
        timeline: '3–4 sem',
        agent: 'Balla',
        agentAvatar: '/agents/balla-3d.png',
        metrics: [{ label: 'Écart caisse', value: '0 FCFA' }, { label: 'Colis suivis', value: '100%' }],
        prospectScript: [
          { from: 'boss', text: 'Résumé de la journée ?' },
          { from: 'agent', text: '📊 **Rapport SpeedLiv — aujourd\'hui**\n\n47 livraisons · 235 000 FCFA encaissés · 2 non livrés (clients absents)' },
          { from: 'boss', text: 'Qui n\'a pas été livré ?' },
          { from: 'agent', text: '#0034 — Mme Bella (reprogrammé demain 9h)\n#0041 — M. Nkoa (reprogrammé demain 10h)\n\nMessages envoyés automatiquement ✅' },
        ],
        bossScript: [
          { from: 'agent', text: '📊 **Tableau de bord temps réel — SpeedLiv**\n\n🚚 12 livreurs actifs en ce moment\n📦 34/47 colis livrés (72%)\n💰 168 000 FCFA encaissés à 16h' },
          { from: 'boss', text: 'Qui est le plus rapide aujourd\'hui ?' },
          { from: 'agent', text: '🏆 **Jean-Baptiste** — 14 livraisons, 22 min/livraison en moyenne\n\n2ème : Patrick — 11 livraisons, 28 min\n3ème : Serge — 9 livraisons, 31 min' },
          { from: 'boss', text: 'Et les écarts de caisse ?' },
          { from: 'agent', text: '**0 FCFA d\'écart** — 8ème semaine consécutive ✅\n\nTout est encaissé via Mobile Money. Le cash ne circule plus.' },
        ],
      },
      {
        id: 'log_report_livreur',
        name: 'Rapport Performance Livreur',
        description: 'Chaque soir, rapport automatique par livreur : nombre de livraisons, cash collecté, photos de preuves, incidents signalés.',
        pillar: 'backend_office',
        icon: BarChart,
        tags: ['KPIs', 'Automatisé', 'WhatsApp'],
        effort: 'Simple',
        timeline: '1 sem',
        agent: 'Balla',
        agentAvatar: '/agents/balla-3d.png',
        metrics: [{ label: 'Temps reporting', value: '0h' }, { label: 'Fraude', value: '-95%' }],
        prospectScript: [
          { from: 'client', text: 'Je voudrais savoir où en est ma livraison.' },
          { from: 'agent', text: 'Bonjour ! Votre colis est actuellement **en cours de livraison** 🚚\n\nLivreur : Jean-Baptiste — arrivée estimée dans **40 min**.' },
          { from: 'client', text: 'Super merci !' },
          { from: 'agent', text: 'Je vous envoie un message quand il est à 15 min de chez vous 📍' },
        ],
        bossScript: [
          { from: 'agent', text: '📋 **Rapport livreur — Jean-Baptiste — 3 juin**\n\n📦 14 livraisons · 💰 68 500 FCFA · 📸 14/14 photos · ⏱️ 22 min/livraison' },
          { from: 'boss', text: 'Et Patrick ?' },
          { from: 'agent', text: '📋 **Patrick — 3 juin**\n\n📦 11 livraisons · 💰 52 000 FCFA · ⚠️ 2 photos manquantes\n\nRappel envoyé. Je vous alerte si récidive.' },
          { from: 'boss', text: 'Combien de temps je passais à faire ces rapports avant ?' },
          { from: 'agent', text: 'Environ **2h/soir** en moyenne pour collecter les infos livreurs.\nMaintenant : **0 minute** — tout est automatique chaque soir à 20h ✅' },
        ],
      },
      {
        id: 'log_notif_client',
        name: 'Suivi Colis Client (WhatsApp)',
        description: 'Notifications automatiques à chaque étape : expédition, en route, arrivée imminente (J-1h), livraison confirmée.',
        pillar: 'communication_client',
        icon: Bell,
        tags: ['Notifications', 'WhatsApp', 'Temps réel'],
        effort: 'Simple',
        timeline: '1 sem',
        agent: 'Balla',
        agentAvatar: '/agents/balla-3d.png',
        metrics: [{ label: 'Satisfaction client', value: '4.9/5' }, { label: 'Appels entrants', value: '-70%' }],
        prospectScript: [
          { from: 'agent', text: 'Bonjour Mme Bella ! 📦 Votre colis #0034 est en route. Livraison prévue entre **14h et 16h** aujourd\'hui.' },
          { from: 'client', text: 'Je ne suis pas là à 14h, possible de décaler ?' },
          { from: 'agent', text: 'Pas de problème ! À quelle heure êtes-vous disponible ?' },
          { from: 'client', text: 'Après 17h.' },
          { from: 'agent', text: 'Noté ! Votre livreur repassera après **17h** ✅. Message de rappel 30 min avant.' },
        ],
        bossScript: [
          { from: 'agent', text: '📊 **Rapport livraisons — aujourd\'hui**\n\n47 colis expédiés · 44 livrés · 3 reprogrammés' },
          { from: 'boss', text: 'Pourquoi 3 reprogrammés ?' },
          { from: 'agent', text: '2 clients absents (repassage demain matin confirmé)\n1 adresse incorrecte (client contacté, adresse corrigée)\n\nAucune perte. Tout est tracé ✅' },
          { from: 'boss', text: 'Combien d\'appels clients on a reçus ?' },
          { from: 'agent', text: '**3 appels seulement** aujourd\'hui vs 21 en moyenne avant Ozirus.\n\nLes notifications WhatsApp automatiques ont réduit les appels de **-86%**.' },
        ],
      },
      {
        id: 'log_cod_payment',
        name: 'Cash on Delivery Mobile Money',
        description: 'L\'agent envoie un lien de paiement Mobile Money avant la livraison. Validation automatique. Le cash ne circule plus physiquement.',
        pillar: 'communication_client',
        icon: CreditCard,
        tags: ['Mobile Money', 'COD', 'Sécurité'],
        effort: 'Moyen',
        timeline: '2 sem',
        agent: 'Balla',
        agentAvatar: '/agents/balla-3d.png',
        metrics: [{ label: 'Cash sécurisé', value: '2M XAF/jour' }, { label: 'Risque vol', value: '0%' }],
        prospectScript: [
          { from: 'agent', text: 'Bonjour ! Votre commande #0041 arrive dans **30 minutes**. Montant : **12 500 FCFA**.\n\n📱 Orange Money · MTN Momo · Wave' },
          { from: 'client', text: 'Je paye par Orange Money.' },
          { from: 'agent', text: 'Envoyez **12 500 FCFA** au **697 XX XX XX**. Le livreur sera notifié dès confirmation ✅' },
          { from: 'client', text: 'C\'est fait, voici ma capture.' },
          { from: 'agent', text: 'Paiement validé ✅ Livreur notifié. Il arrive dans ~25 min. Bonne réception !' },
        ],
        bossScript: [
          { from: 'agent', text: '💰 **Encaissements du jour — SpeedLiv**\n\n47 livraisons · **587 500 FCFA** encaissés via Mobile Money\n0 cash physique · 0 écart de caisse' },
          { from: 'boss', text: 'Avant on avait combien d\'écart par semaine ?' },
          { from: 'agent', text: 'Avant Ozirus : **~45 000 FCFA d\'écart/semaine** en moyenne.\nDepuis Ozirus : **0 FCFA d\'écart** sur les 8 dernières semaines.\n\nSoit **360 000 FCFA récupérés** sur 2 mois.' },
          { from: 'boss', text: 'Parfait.' },
          { from: 'agent', text: 'Rapport comptable complet en PDF disponible dans votre dashboard 📊' },
        ],
      },
      {
        id: 'log_proof_delivery',
        name: 'Preuve de Livraison Photo',
        description: 'Le livreur envoie une photo via WhatsApp à la livraison. L\'agent l\'archive automatiquement et envoie une confirmation au client.',
        pillar: 'fidelisation',
        icon: ClipboardCheck,
        tags: ['Photo', 'Archive', 'Preuves'],
        effort: 'Simple',
        timeline: '3 jours',
        agent: 'Balla',
        agentAvatar: '/agents/balla-3d.png',
        metrics: [{ label: 'Litiges', value: '-98%' }, { label: 'Preuve 100%', value: 'Archivée' }],
        prospectScript: [
          { from: 'client', text: 'Bonjour, j\'ai commandé mais je n\'ai rien reçu.' },
          { from: 'agent', text: 'Bonjour ! Je vérifie votre livraison... 📦\n\nCommande #0041 — livrée hier à **17h12** par Jean-Baptiste.\nUne photo de preuve a été prise à votre adresse.' },
          { from: 'client', text: 'Ah oui c\'est vrai, j\'avais oublié. Merci !' },
          { from: 'agent', text: 'Pas de souci 😊 N\'hésitez pas si vous avez d\'autres questions !' },
        ],
        bossScript: [
          { from: 'agent', text: '📸 **Preuve de livraison reçue**\n\nColis #0041 — Jean-Baptiste — 17h12\nPhoto géolocalisée archivée ✅' },
          { from: 'boss', text: 'Un client conteste une livraison ?' },
          { from: 'agent', text: 'Aucune contestation aujourd\'hui. Ce mois : **2 litiges** déclarés.\n\nLes 2 ont été résolus en **< 3 min** grâce aux preuves photo horodatées. Les clients ont retiré leur plainte.' },
          { from: 'boss', text: 'Avant on en avait combien ?' },
          { from: 'agent', text: 'Avant Ozirus : **~18 litiges/mois**. Maintenant : **2**.\nSoit **-89% de litiges** 🛡️' },
        ],
      },
      {
        id: 'log_loyalty_ecom',
        name: 'Cashback & Fidélisation E-com',
        description: 'Pour les e-commerçants partenaires : programme de cashback automatique pour les clients fidèles, envoyé via WhatsApp après chaque commande.',
        pillar: 'fidelisation',
        icon: BadgePercent,
        tags: ['Cashback', 'E-commerce', 'WhatsApp'],
        effort: 'Moyen',
        timeline: '1–2 sem',
        agent: 'Balla',
        agentAvatar: '/agents/balla-3d.png',
        metrics: [{ label: 'Commandes répétées', value: '+45%' }, { label: 'LTV client', value: '+30%' }],
        prospectScript: [
          { from: 'agent', text: 'Merci Éric ! 🎉 Vous venez de recevoir **500 FCFA de cashback** sur votre prochain achat.' },
          { from: 'client', text: 'C\'est automatique ?' },
          { from: 'agent', text: 'Oui ! À chaque livraison réussie, cashback crédité automatiquement. Dès **5 000 FCFA cumulés**, vous pouvez les utiliser sur une prochaine commande.' },
          { from: 'client', text: 'J\'ai combien en ce moment ?' },
          { from: 'agent', text: '**2 750 FCFA** de cashback 💰 — encore 2 commandes pour le seuil !' },
        ],
        bossScript: [
          { from: 'agent', text: '💰 **Programme cashback — ce mois**\n\n183 clients actifs · 4 320 FCFA distribués en moyenne/client' },
          { from: 'boss', text: 'Est-ce que ça génère vraiment plus de commandes ?' },
          { from: 'agent', text: 'Oui. Les clients avec cashback commandent en moyenne **2.8x plus souvent** que les autres.\n\nCA additionnel généré ce mois : **+1 240 000 FCFA**\nvs coût cashback distribué : **790 000 FCFA**\n\nROI net : **+57%** 🎯' },
        ],
      },
    ],
    intents: [
      {
        id: 'logistics_cod',
        name: 'Cash on Delivery Automatisé',
        icon: DollarSign,
        description: 'Gérez vos livreurs et vos encaissements WhatsApp sans erreur humaine.',
        agentName: 'Balla',
        agentAvatar: '/agents/balla-3d.png',
        agentRole: 'Ops Agent',
        impact: 'Récupération de 100% du cash',
        metrics: [
          { label: 'Ecart de caisse', value: '0F', trend: 'down', change: '-100%' },
          { label: 'Preuves Liv.', value: '100%', trend: 'up', change: 'Total' },
          { label: 'Satisfaction', value: '4.9/5', trend: 'up', change: '+0.4' },
        ],
        qrData: {
          label: 'Suivre & Payer mon colis',
          description: 'Sur le ticket de caisse ou le SMS d\'expédition.',
          placeholderUrl: 'https://api.qrserver.com/v1/create-qr-code/?size=300x300&data=ozirus_logistics_cod&color=F59E0B',
        },
        valueProp: {
          title: 'Ce que gagne le transporteur',
          points: [
            'Validation photo de la livraison via WhatsApp',
            'Encaissement Mobile Money instantané (le cash ne circule plus)',
            'Rapport de performance livreur généré chaque soir',
          ],
          mainMetric: 'Sécurisation de 2M XAF / jour de flux cash',
        },
        schema: [
          { id: 'l1', type: 'trigger', label: 'Colis en Route', sublabel: 'Départ entrepôt', icon: Package, position: { x: 10, y: 50 }, status: 'success' },
          { id: 'l2', type: 'process', label: 'Alerte Client', sublabel: 'WhatsApp auto J-1h', icon: MessageSquare, agent: 'Balla', position: { x: 30, y: 50 }, status: 'active' },
          { id: 'l3', type: 'action', label: 'Paiement MM', sublabel: 'Paiement à la porte', icon: Smartphone, position: { x: 55, y: 30 }, status: 'success' },
          { id: 'l4', type: 'action', label: 'Photo de Preuve', sublabel: 'Livreur scanne le colis', icon: Smartphone, position: { x: 55, y: 70 }, status: 'success' },
          { id: 'l5', type: 'result', label: 'Cash Validé', sublabel: 'Sync Comptable', icon: CheckCircle2, position: { x: 85, y: 50 }, status: 'success' },
        ],
      },
    ],
  },

  // ─── BOUTIQUE & RETAIL ─────────────────────────────────────────────────────
  {
    id: 'retail',
    name: 'Boutique & Retail',
    icon: ShoppingBag,
    color: '#10B981',
    tagline: 'Vendez plus, gérez mieux.',
    deliverables: [
      {
        id: 'retail_stock',
        name: 'Gestion de Stock IA',
        description: 'Inventaire en temps réel avec alertes rupture, suggestions de réapprovisionnement et rapports de rotation des produits.',
        pillar: 'backend_office',
        icon: Package,
        tags: ['Stock', 'Alertes', 'IA'],
        effort: 'Moyen',
        timeline: '2 sem',
        agent: 'Amina',
        agentAvatar: '/agents/amina-3d.png',
        metrics: [{ label: 'Ruptures', value: '0' }, { label: 'Rotation stock', value: '+50%' }],
        prospectScript: [
          { from: 'client', text: 'Vous avez encore des Sneakers Air Max T42 ?' },
          { from: 'agent', text: 'Bonjour ! Il reste **1 exemplaire** en T42. Souhaitez-vous le réserver ?' },
          { from: 'client', text: 'Oui !' },
          { from: 'agent', text: 'Réservé pour vous ✅ Je vous envoie les infos de paiement dans un instant.' },
        ],
        bossScript: [
          { from: 'agent', text: '⚠️ **Alerte stock — Boutique Ngo Style**\n\nSneakers Air Max T42 : **dernier exemplaire**. Rupture estimée demain.' },
          { from: 'boss', text: 'Commande 10 paires.' },
          { from: 'agent', text: 'Commande envoyée à SneakersPro Cameroun ✅\n6 × T42 · 4 × T43 · Livraison **jeudi matin**\n\nJe bloque le dernier T42 pour Mme Nguemo qui était en attente ?' },
          { from: 'boss', text: 'Oui fais-le.' },
          { from: 'agent', text: 'Réservé pour Mme Nguemo ✅ Elle est notifiée automatiquement.' },
        ],
      },
      {
        id: 'retail_analytics',
        name: 'Analytics Ventes & Tendances',
        description: 'Dashboard avec les produits best-sellers, les horaires de pic, les segments clients et les tendances du marché.',
        pillar: 'backend_office',
        icon: BarChart,
        tags: ['Analytics', 'Dashboard', 'Tendances'],
        effort: 'Moyen',
        timeline: '1–2 sem',
        agent: 'Amina',
        agentAvatar: '/agents/amina-3d.png',
        metrics: [{ label: 'Visibilité', value: 'Totale' }, { label: 'Décisions data', value: '100%' }],
        prospectScript: [
          { from: 'client', text: 'C\'est quoi vos meilleures ventes du mois ?' },
          { from: 'agent', text: 'Bonjour ! Ce mois chez **Boutique Ngo Style** :\n\n🏆 Robes longues (+34%)\n🥈 Sacs à main (+22%)\n🥉 Chaussures talon\n\nPic de vente : Samedi 14h–17h 📈' },
          { from: 'client', text: 'Merci !' },
          { from: 'agent', text: 'À votre service 😊' },
        ],
        bossScript: [
          { from: 'agent', text: '📊 **Rapport hebdo — Boutique Ngo Style**\n\n🏆 Best-sellers : Robes longues, Sacs à main\n⏰ Pic : Samedi 14h–17h\n👥 47 nouveaux clients' },
          { from: 'boss', text: 'Ce qui se vend pas ?' },
          { from: 'agent', text: '**Ceintures homme** — 2 ventes en 30 jours.\n\nJe conseille une promo flash ce weekend pour écouler le stock avant de réassortir. Voulez-vous que je prépare le message pour vos clients ?' },
          { from: 'boss', text: 'Oui.' },
          { from: 'agent', text: 'Campagne promo ceintures prête ✅ Envoi programmé samedi 9h à 312 clients.' },
        ],
      },
      {
        id: 'retail_catalog_wa',
        name: 'Catalogue WhatsApp & Commande',
        description: 'Le client découvre et commande directement sur WhatsApp. L\'agent gère le catalogue, les stocks, l\'upsell et le lien de paiement.',
        pillar: 'communication_client',
        icon: MessageSquare,
        tags: ['WhatsApp', 'Catalogue', 'Commande'],
        effort: 'Avancé',
        timeline: '2–3 sem',
        agent: 'Amina',
        agentAvatar: '/agents/amina-3d.png',
        metrics: [{ label: 'Ventes 24h/24', value: '100%' }, { label: 'Panier moyen', value: '+35%' }],
        prospectScript: [
          { from: 'client', text: 'Bonjour, vous avez des robes longues ?' },
          { from: 'agent', text: 'Bonjour ! Je suis Amina de **Boutique Ngo Style** 👗\n\n1. Robe batik fleurie — **18 500 FCFA** (T36–T44)\n2. Robe satinée noire — **22 000 FCFA** (T38–T42)\n3. Robe africaine imprimée — **15 000 FCFA** (Taille unique)\n\nLaquelle vous intéresse ?' },
          { from: 'client', text: 'La satinée noire en T40.' },
          { from: 'agent', text: 'Robe satinée noire T40 disponible ✅\nTotal : **24 000 FCFA** (robe + livraison)\n\nPaiement MTN Momo ?' },
          { from: 'client', text: 'Oui.' },
          { from: 'agent', text: 'Envoyez **24 000 FCFA** au **677 XX XX XX**. Livraison demain 10h–14h 🚚' },
        ],
        bossScript: [
          { from: 'agent', text: '🛒 **Ventes du jour — Boutique Ngo Style**\n\n23 commandes · **387 000 FCFA** de CA\n⏰ 14 commandes hors heures d\'ouverture (61%)' },
          { from: 'boss', text: 'Les commandes hors horaires c\'est toutes via WhatsApp ?' },
          { from: 'agent', text: 'Oui, **100% automatisé** par Amina.\n\nAvant Ozirus : 0 vente après 18h.\nMaintenant : **+61% de CA hors horaires**.\n\nCe mois : **+1 240 000 FCFA** de CA additionnel.' },
          { from: 'boss', text: 'Top.' },
          { from: 'agent', text: 'Je vous envoie le rapport hebdomadaire complet lundi matin ✅' },
        ],
      },
      {
        id: 'retail_abandon_cart',
        name: 'Relance Paniers Abandonnés',
        description: 'Si un client s\'arrête en plein achat, l\'agent le relance automatiquement 2h plus tard avec un rappel et parfois une promo.',
        pillar: 'communication_client',
        icon: Bell,
        tags: ['Relance', 'Panier', 'Auto'],
        effort: 'Simple',
        timeline: '3 jours',
        agent: 'Amina',
        agentAvatar: '/agents/amina-3d.png',
        metrics: [{ label: 'Récupération', value: '+22%' }, { label: 'CA récupéré', value: '+150k/mois' }],
        prospectScript: [
          { from: 'agent', text: 'Bonjour Carine ! 👋 La **Robe satinée noire T40** que vous avez regardée est toujours disponible.' },
          { from: 'agent', text: 'Et pour vous aujourd\'hui : **-10%** 🎁\nPrix : **19 800 FCFA** au lieu de 22 000 FCFA' },
          { from: 'client', text: 'Oh j\'avais oublié ! Je prends.' },
          { from: 'agent', text: 'Super ! **21 800 FCFA** au **677 XX XX XX** MTN Momo. Confirmation dès réception ✅' },
        ],
        bossScript: [
          { from: 'agent', text: '🔔 **Paniers abandonnés — cette semaine**\n\n37 paniers détectés · 9 convertis (24%)\nCA récupéré : **156 000 FCFA**' },
          { from: 'boss', text: 'C\'est quoi la conversion avant ?' },
          { from: 'agent', text: 'Avant Ozirus : **0%** (pas de relance).\n\nAvec Ozirus : **22–24%** de récupération automatique.\n\nSoit **+150 000 FCFA/mois** sans aucune action de votre part.' },
        ],
      },
      {
        id: 'retail_loyalty_points',
        name: 'Points de Fidélité & Récompenses',
        description: 'Chaque achat génère des points. L\'agent notifie le client, gère les récompenses et envoie des offres anniversaires.',
        pillar: 'fidelisation',
        icon: Star,
        tags: ['Points', 'Récompenses', 'Anniversaire'],
        effort: 'Moyen',
        timeline: '1–2 sem',
        agent: 'Amina',
        agentAvatar: '/agents/amina-3d.png',
        metrics: [{ label: 'Clients actifs', value: '+60%' }, { label: 'Fréquence achat', value: 'x2.5' }],
        prospectScript: [
          { from: 'agent', text: 'Merci Carine ! 🎉 **220 points** crédités (1 point = 100 FCFA achetés).' },
          { from: 'agent', text: 'Solde : **1 850 pts** — encore 150 pts pour **-15% sur votre prochain achat** !' },
          { from: 'client', text: 'C\'est quand mon anniversaire dans le système ?' },
          { from: 'agent', text: 'Le **18 août** 🎂 Une surprise vous attend ce jour-là !' },
        ],
        bossScript: [
          { from: 'agent', text: '⭐ **Programme fidélité — ce mois**\n\n312 clients actifs · 4 récompenses distribuées · 28 offres anniversaire envoyées' },
          { from: 'boss', text: 'Les clients fidèles achètent vraiment plus ?' },
          { from: 'agent', text: 'Oui. Clients avec points : **2.5x plus de commandes/mois** que les non-inscrits.\n\nLeur panier moyen : **+38%** plus élevé.\n\nTop cliente du mois : Mme Essomba — 8 achats, **124 500 FCFA** dépensés.' },
        ],
      },
      {
        id: 'retail_vip_segment',
        name: 'Segment VIP & Ventes Privées',
        description: 'Identification automatique des clients VIP. Accès à des ventes privées, nouveautés en avant-première et traitement prioritaire.',
        pillar: 'fidelisation',
        icon: Sparkles,
        tags: ['VIP', 'Segmentation', 'Exclusivité'],
        effort: 'Moyen',
        timeline: '2 sem',
        agent: 'Amina',
        agentAvatar: '/agents/amina-3d.png',
        metrics: [{ label: 'LTV VIP', value: 'x4' }, { label: 'Satisfaction', value: '4.9/5' }],
        prospectScript: [
          { from: 'agent', text: 'Bonjour Isabelle ! 💎 En tant que cliente VIP de **Boutique Ngo Style**, vous êtes invitée à notre vente privée de samedi.' },
          { from: 'agent', text: '**-20% sur tout** de 10h à 12h — exclusivement pour nos 30 meilleures clientes. Intéressée ?' },
          { from: 'client', text: 'Absolument ! C\'est en boutique ?' },
          { from: 'agent', text: 'En boutique ET sur WhatsApp 👗 Catalogue exclusif vendredi soir ✨' },
        ],
        bossScript: [
          { from: 'agent', text: '💎 **Vente privée VIP — Résultats**\n\n30 invitées · 24 présentes (80%) · **680 000 FCFA** de CA en 2h' },
          { from: 'boss', text: 'Et les clientes VIP vs les normales ?' },
          { from: 'agent', text: 'VIP : panier moyen **28 400 FCFA**\nNon-VIP : panier moyen **7 200 FCFA**\n\nLTV VIP = **x4** sur 12 mois.\n\nVos 30 VIP génèrent **38% de votre CA total** à elles seules.' },
        ],
      },
    ],
    intents: [
      {
        id: 'retail_catalog',
        name: 'Catalogue WhatsApp & Stock IA',
        icon: Layers,
        description: 'Vendez en automatique sur WhatsApp même quand vous dormez.',
        agentName: 'Amina',
        agentAvatar: '/agents/amina-3d.png',
        agentRole: 'Sales Assistant',
        impact: 'Ventes 24h/24 sans personnel',
        metrics: [
          { label: 'Réponses Auto', value: '100%', trend: 'up', change: 'Total' },
          { label: 'Panier Moyen', value: '+35%', trend: 'up', change: '+5k' },
          { label: 'Reach Social', value: 'x10', trend: 'up', change: 'Viral' },
        ],
        qrData: {
          label: 'Acheter sur WhatsApp',
          description: 'Sur vos flyers, bio Instagram et boutique physique.',
          placeholderUrl: 'https://api.qrserver.com/v1/create-qr-code/?size=300x300&data=ozirus_retail_catalog&color=10B981',
        },
        valueProp: {
          title: 'Ce que gagne la boutique',
          points: [
            'Inventaire synchronisé en temps réel sur WhatsApp',
            'Upsell automatique (IA propose des articles assortis)',
            'Relance des paniers abandonnés après 2h',
          ],
          mainMetric: '+30% de CA généré hors heures d\'ouverture',
        },
        schema: [
          { id: 'r1', type: 'trigger', label: 'Consultation', sublabel: 'Client demande un prix', icon: MessageSquare, position: { x: 10, y: 50 }, status: 'success' },
          { id: 'r2', type: 'process', label: 'Assistant Vente', sublabel: 'Amina guide le client', icon: Users, agent: 'Amina', position: { x: 35, y: 50 }, status: 'active' },
          { id: 'r3', type: 'action', label: 'Vérif Stock', sublabel: 'Automatique 24/7', icon: ClipboardCheck, position: { x: 60, y: 20 }, status: 'success' },
          { id: 'r4', type: 'action', label: 'Lien Paiement', sublabel: 'Mobile Money Pay', icon: Wallet, position: { x: 60, y: 80 }, status: 'success' },
          { id: 'r5', type: 'result', label: 'Commande Prête', sublabel: 'Alerte Livreur', icon: TruckIcon, position: { x: 85, y: 50 }, status: 'success' },
        ],
      },
    ],
  },

  // ─── B2B & SERVICES ────────────────────────────────────────────────────────
  {
    id: 'b2b',
    name: 'B2B & Services',
    icon: Briefcase,
    color: '#3B82F6',
    tagline: 'L\'excellence opérationnelle pour experts.',
    deliverables: [
      {
        id: 'b2b_crm_pipeline',
        name: 'CRM & Pipeline Commercial',
        description: 'Suivi de chaque opportunité commerciale de la prospection à la signature. Scoring automatique, relances planifiées, prévision de revenus.',
        pillar: 'backend_office',
        icon: GitBranch,
        tags: ['CRM', 'Pipeline', 'Prévision'],
        effort: 'Avancé',
        timeline: '3–5 sem',
        agent: 'Solène',
        agentAvatar: '/agents/solene-3d.png',
        metrics: [{ label: 'Taux conversion', value: '+45%' }, { label: 'Cycle vente', value: '-30%' }],
        prospectScript: [
          { from: 'boss', text: 'Pipeline du jour ?' },
          { from: 'agent', text: '📊 **8 opportunités actives**\n🔴 Chaud : Syscom, MTB Group, Fokou\n🟡 Tiède : Camtel, SCDP, CCEI Bank\n🔵 Froid : Total Énergie, Eneo' },
          { from: 'boss', text: 'Score de Syscom ?' },
          { from: 'agent', text: 'Syscom — **92/100** 🎯\n\n✅ Budget 4,5M · ✅ DG identifié · ✅ Démo faite\n⏳ Board vendredi. Je relance à 10h ?' },
          { from: 'boss', text: 'Oui.' },
          { from: 'agent', text: 'Relance Syscom programmée vendredi 10h ✅ Résumé exécutif préparé pour M. Biyong.' },
        ],
        bossScript: [
          { from: 'agent', text: '📊 **Pipeline Expertise Conseil**\n\n8 opportunités · Valeur totale : **34,5M FCFA**\n3 signatures prévues ce mois' },
          { from: 'boss', text: 'Combien de temps je passais à gérer ça avant ?' },
          { from: 'agent', text: 'Avant : environ **3h/jour** de suivi manuel.\nMaintenant : **15 min de revue** le matin, tout le reste est automatisé.\n\nTaux de conversion : **+45%** depuis Ozirus.' },
        ],
      },
      {
        id: 'b2b_facturation',
        name: 'Facturation & Suivi Paiements',
        description: 'Génération automatique des factures, envoi par WhatsApp/email, relances de paiement et alertes de retard.',
        pillar: 'backend_office',
        icon: Receipt,
        tags: ['Facturation', 'Relances', 'Auto'],
        effort: 'Simple',
        timeline: '1 sem',
        agent: 'Solène',
        agentAvatar: '/agents/solene-3d.png',
        metrics: [{ label: 'Paiements en retard', value: '-80%' }, { label: 'Temps ADV', value: '-5h/sem' }],
        prospectScript: [
          { from: 'client', text: 'Bonjour, je voudrais votre facture pour notre audit.' },
          { from: 'agent', text: 'Bonjour M. Biyong ! Facture **F-2025-041** générée :\n\nMission d\'audit Syscom — **1 800 000 FCFA**\nÉchéance : 7 juin 2025\n\nEnvoyée sur WhatsApp et email ✅' },
          { from: 'client', text: 'Bien reçu.' },
          { from: 'agent', text: 'Je vous enverrai un rappel 3 jours avant l\'échéance. Bon après-midi !' },
        ],
        bossScript: [
          { from: 'agent', text: '⚠️ **Facture F-2025-041** (Syscom — 1 800 000 FCFA) — échéance dans 3 jours.' },
          { from: 'boss', text: 'Relance.' },
          { from: 'agent', text: 'Relance envoyée à M. Biyong (WhatsApp + email) ✅\n\nSi pas de réponse dans 48h, je vous alerte pour un appel direct.' },
          { from: 'boss', text: 'Combien de factures en retard ce mois ?' },
          { from: 'agent', text: 'Ce mois : **2 factures en retard** (vs 11 le mois avant Ozirus).\n\n**-82%** de retards. Total créances récupérées : **+4 200 000 FCFA**.' },
        ],
      },
      {
        id: 'b2b_kyc',
        name: 'KYC & Qualification Prospect IA',
        description: 'L\'agent interview le prospect, collecte les documents légaux, vérifie leur validité et trie les sérieux des curieux.',
        pillar: 'communication_client',
        icon: UserCheck,
        tags: ['KYC', 'Compliance', 'WhatsApp'],
        effort: 'Avancé',
        timeline: '2–3 sem',
        agent: 'Solène',
        agentAvatar: '/agents/solene-3d.png',
        metrics: [{ label: 'Dossiers complets', value: '98%' }, { label: 'Temps qualification', value: '-85%' }],
        prospectScript: [
          { from: 'client', text: 'Bonjour, je cherche un cabinet pour ma société import-export.' },
          { from: 'agent', text: 'Bonjour ! Je suis Solène d\'**Expertise Conseil**.\n\nPour vous orienter : votre principal besoin est ?\n1️⃣ Comptabilité\n2️⃣ Optimisation fiscale\n3️⃣ Accompagnement juridique' },
          { from: 'client', text: '1 et 2.' },
          { from: 'agent', text: 'Parfait. Pour préparer votre dossier, j\'aurais besoin de :\n\n📄 Registre de commerce · 📄 NIU · 📄 Derniers états financiers\n\nEnvoyez-les ici ?' },
          { from: 'client', text: 'Oui je vous envoie ça.' },
          { from: 'agent', text: 'Reçu ! Je vérifie et vous confirme sous 2h. Un expert vous contactera pour le RDV de qualification ✅' },
        ],
        bossScript: [
          { from: 'agent', text: '✅ **Nouveau prospect qualifié — Syscom SARL**\n\nSecteur : Import-export · Budget estimé : 3–5M FCFA\nDossier complet reçu et vérifié automatiquement.' },
          { from: 'boss', text: 'Combien de prospects traités cette semaine ?' },
          { from: 'agent', text: '**23 contacts** reçus cette semaine.\n\n✅ 8 qualifiés et transmis aux experts\n❌ 15 non retenus (budget insuffisant, secteur hors périmètre)\n\nVous n\'avez géré **aucun appel de pré-qualification**.' },
        ],
      },
      {
        id: 'b2b_support',
        name: 'Support Client IA 24h/24',
        description: 'Agent IA capable de répondre aux questions techniques, aux demandes de devis standards et d\'escalader vers un humain si nécessaire.',
        pillar: 'communication_client',
        icon: Headset,
        tags: ['Support', '24h/24', 'Escalade'],
        effort: 'Moyen',
        timeline: '2 sem',
        agent: 'Solène',
        agentAvatar: '/agents/solene-3d.png',
        metrics: [{ label: 'Résolution auto', value: '75%' }, { label: 'Satisfaction', value: '4.7/5' }],
        prospectScript: [
          { from: 'client', text: 'Bonsoir, j\'aurais besoin d\'un devis pour un audit comptable.' },
          { from: 'agent', text: 'Bonsoir ! Je suis Solène. Votre CA annuel :\n1️⃣ < 50M FCFA\n2️⃣ 50–200M FCFA\n3️⃣ > 200M FCFA' },
          { from: 'client', text: '2.' },
          { from: 'agent', text: 'Audit complet pour 50–200M FCFA : **850 000 à 1 200 000 FCFA**.\n\nUn expert vous rappelle demain matin ?' },
          { from: 'client', text: 'Oui.' },
          { from: 'agent', text: 'RDV confirmé — M. Tagne vous appelle demain 9h–10h ✅' },
        ],
        bossScript: [
          { from: 'agent', text: '🤖 **Support client IA — cette semaine**\n\n47 questions traitées · 35 résolues automatiquement (74%) · 12 escaladées à un expert' },
          { from: 'boss', text: 'Les 12 escaladées c\'était quoi ?' },
          { from: 'agent', text: '8 demandes de devis complexes (transmises à M. Tagne)\n4 questions juridiques spécifiques (transmises à Mme Fouda)\n\nTemps moyen d\'escalade : **< 2h**. Aucune demande sans réponse.' },
          { from: 'boss', text: 'Satisfaction ?' },
          { from: 'agent', text: '**4.7/5** de satisfaction moyenne cette semaine 🌟' },
        ],
      },
      {
        id: 'b2b_onboarding',
        name: 'Onboarding Client Automatisé',
        description: 'Séquence de bienvenue après signature : présentation de l\'équipe, accès aux outils, planning du projet, check-ins automatiques.',
        pillar: 'fidelisation',
        icon: BookOpen,
        tags: ['Onboarding', 'Séquence', 'Auto'],
        effort: 'Moyen',
        timeline: '1–2 sem',
        agent: 'Solène',
        agentAvatar: '/agents/solene-3d.png',
        metrics: [{ label: 'Churn J30', value: '-90%' }, { label: 'Satisfaction onboarding', value: '4.8/5' }],
        prospectScript: [
          { from: 'agent', text: 'Bienvenue M. Biyong ! 🎉 Votre mission avec **Expertise Conseil** démarre.' },
          { from: 'agent', text: 'Votre équipe :\n👤 M. Tagne — Expert référent\n👤 Mme Atangana — Assistante\n📞 699 XX XX XX' },
          { from: 'agent', text: 'Planning :\n📅 Sem 1 : Collecte docs\n📅 Sem 2–3 : Analyse\n📅 Sem 4 : Restitution\n\nPoint hebdo chaque lundi ✅' },
          { from: 'client', text: 'Parfait, merci !' },
          { from: 'agent', text: 'À lundi pour le premier point ! Bonne journée M. Biyong.' },
        ],
        bossScript: [
          { from: 'agent', text: '🎉 **Nouveau client onboardé — Syscom SARL**\n\nSéquence de bienvenue envoyée automatiquement.\nÉquipe assignée, planning partagé, accès configurés ✅' },
          { from: 'boss', text: 'Avant combien de temps pour onboarder un client ?' },
          { from: 'agent', text: 'Avant : **1–2 jours** de mails et d\'appels pour tout configurer.\nMaintenant : **automatique en moins d\'1h** après signature.\n\nChurn J30 depuis : **-90%**.' },
        ],
      },
      {
        id: 'b2b_nps',
        name: 'NPS & Upsell Automatique',
        description: 'Enquêtes NPS automatiques à J30, J90 et J365. Les promoteurs sont invités à laisser un avis. Les détracteurs sont contactés par un humain.',
        pillar: 'fidelisation',
        icon: TrendingUp,
        tags: ['NPS', 'Upsell', 'Rétention'],
        effort: 'Simple',
        timeline: '1 sem',
        agent: 'Solène',
        agentAvatar: '/agents/solene-3d.png',
        metrics: [{ label: 'NPS Score', value: '+42pts' }, { label: 'Upsell auto', value: '+25%' }],
        prospectScript: [
          { from: 'agent', text: 'Bonjour M. Biyong ! Votre mission est terminée depuis 30 jours.\n\nDe 0 à 10, recommanderiez-vous **Expertise Conseil** ?' },
          { from: 'client', text: '9/10, très satisfait !' },
          { from: 'agent', text: 'Merci ! 🙏 Un avis Google nous aiderait beaucoup :\n\n👉 g.page/expertise-conseil-yaounde' },
          { from: 'client', text: 'Avec plaisir.' },
          { from: 'agent', text: 'Merci M. Biyong ! 💎\n\nAvez-vous pensé à notre service d\'**optimisation fiscale trimestrielle** ? Vu votre profil : 15–20% d\'économies potentielles. Cela vous intéresse ?' },
        ],
        bossScript: [
          { from: 'agent', text: '📊 **NPS mensuel — Expertise Conseil**\n\n18 enquêtes envoyées · Score moyen : **72/100** (+42 pts vs il y a 6 mois)' },
          { from: 'boss', text: 'Les upsells fonctionnent ?' },
          { from: 'agent', text: 'Ce mois : **6 clients** ont accepté un service additionnel après l\'enquête NPS.\n\nCA upsell généré : **+3 400 000 FCFA**.\nSoit **+25%** de CA récurrent supplémentaire sans action commerciale.' },
          { from: 'boss', text: 'Parfait.' },
          { from: 'agent', text: 'Prochaine vague NPS dans 7 jours. Je vous envoie le rapport complet ✅' },
        ],
      },
    ],
    intents: [
      {
        id: 'b2b_kyc',
        name: 'KYC & Qualification Prospect IA',
        icon: Globe,
        description: 'Qualifiez vos prospects et collectez les documents légaux automatiquement.',
        agentName: 'Solène',
        agentAvatar: '/agents/solene-3d.png',
        agentRole: 'Compliance Agent',
        impact: 'Gain de 2 jours de traitement / dossier',
        metrics: [
          { label: 'Dossiers Complets', value: '98%', trend: 'up', change: '+40%' },
          { label: 'Temps Qualification', value: '-85%', trend: 'up', change: 'Drastique' },
          { label: 'Satisfaction Client', value: '4.7/5', trend: 'up', change: '+0.5' },
        ],
        qrData: {
          label: 'Devenir client / Envoyer dossier',
          description: 'Lien de pré-qualification sur site web ou mail.',
          placeholderUrl: 'https://api.qrserver.com/v1/create-qr-code/?size=300x300&data=ozirus_b2b_kyc&color=3B82F6',
        },
        valueProp: {
          title: 'Ce que gagne l\'expert',
          points: [
            'Vérification automatique de la validité des pièces d\'identité',
            'Triage des prospects selon le score de solvabilité',
            'Prise de rendez-vous uniquement avec les prospects sérieux',
          ],
          mainMetric: 'Zéro temps perdu avec des "curieux"',
        },
        schema: [
          { id: 'b1', type: 'trigger', label: 'Nouvel Intérêt', sublabel: 'Prospect nous contacte', icon: Zap, position: { x: 10, y: 50 }, status: 'success' },
          { id: 'b2', type: 'process', label: 'Interview IA', sublabel: 'Solène pose les questions', icon: MessageSquare, agent: 'Solène', position: { x: 30, y: 30 }, status: 'active' },
          { id: 'b3', type: 'action', label: 'Collecte Doc', sublabel: 'Upload via WhatsApp', icon: FileText, position: { x: 30, y: 70 }, status: 'success' },
          { id: 'b4', type: 'process', label: 'Vérif Compliance', sublabel: 'Analyse auto', icon: ShieldCheck, agent: 'Solène', position: { x: 60, y: 50 }, status: 'active' },
          { id: 'b5', type: 'result', label: 'Dossier Prêt', sublabel: 'Expert peut signer', icon: BarChart, position: { x: 90, y: 50 }, status: 'success' },
        ],
      },
    ],
  },

  // ─── PHARMACIES ───────────────────────────────────────────────────────────
  {
    id: 'pharmacy',
    name: 'Pharmacies',
    icon: Pill,
    color: '#0EA5E9',
    tagline: 'Disponibilité, ordonnance, rappel traitement : tout passe en automatique.',
    deliverables: [
      {
        id: 'pharma_stock_expiry',
        name: 'Stock Médicaments & Péremption',
        description: 'Inventaire temps réel par molécule, seuils critiques, lots proches péremption et suggestions de réassort fournisseur.',
        pillar: 'backend_office',
        icon: Package,
        tags: ['Stock', 'Péremption', 'Lots'],
        effort: 'Avancé',
        timeline: '3–4 sem',
        agent: 'Nora',
        agentAvatar: '/agents/nora-3d.png',
        metrics: [{ label: 'Ruptures', value: '-85%' }, { label: 'Pertes péremption', value: '-60%' }],
        prospectScript: [
          { from: 'client', text: 'Bonjour, vous avez du paracétamol 500 ?' },
          { from: 'agent', text: 'Bonjour ! Oui, **Paracétamol 500 mg** disponible. Il reste **42 boîtes** à la Pharmacie Centrale. Voulez-vous le réserver ?' },
          { from: 'client', text: 'Oui, deux boîtes.' },
          { from: 'agent', text: 'Réservé ✅ Deux boîtes au comptoir pendant 2h. Prix total : **1 000 FCFA**.' },
        ],
        bossScript: [
          { from: 'agent', text: '⚠️ **Alerte stock — Pharmacie Centrale**\n\nAmoxicilline 500 mg : 6 boîtes restantes.\nRupture estimée : demain 11h.' },
          { from: 'boss', text: 'Commande combien ?' },
          { from: 'agent', text: 'Recommandation : **40 boîtes** selon la rotation des 14 derniers jours.\n\nAussi : 12 lots de sirop enfant expirent dans 28 jours. Je prépare une promo encadrée ?' },
          { from: 'boss', text: 'Oui.' },
          { from: 'agent', text: 'Réassort préparé et campagne lots courts prête ✅ Validation finale requise avant envoi.' },
        ],
      },
      {
        id: 'pharma_sales_dashboard',
        name: 'Dashboard Ventes & Marges',
        description: 'Pilotage quotidien : CA, marge par famille, ventes remboursées, produits à forte rotation et ruptures évitées.',
        pillar: 'backend_office',
        icon: LayoutDashboard,
        tags: ['CA', 'Marge', 'Pilotage'],
        effort: 'Moyen',
        timeline: '2 sem',
        agent: 'Nora',
        agentAvatar: '/agents/nora-3d.png',
        metrics: [{ label: 'Marge visible', value: '100%' }, { label: 'Décisions stock', value: 'x3' }],
        prospectScript: [
          { from: 'boss', text: 'Résumé de la journée ?' },
          { from: 'agent', text: '📊 **Pharmacie Centrale — aujourd’hui**\n\nCA : **612 400 FCFA** · Marge estimée : **27%**\nTop ventes : Antalgiques, antibiotiques, vitamines.\n3 ruptures évitées grâce aux alertes.' },
        ],
        bossScript: [
          { from: 'agent', text: '📊 **Rapport hebdo pharmacie**\n\nCA : **3,8M FCFA** (+11%)\nMarge : **1,04M FCFA**\nRuptures critiques : 2\nLots à surveiller : 7' },
          { from: 'boss', text: 'Qu’est-ce qui tire la marge ?' },
          { from: 'agent', text: 'Les compléments et produits bébé génèrent **38% de la marge** pour seulement 21% du CA.\n\nJe recommande de les mettre en avant au comptoir et sur WhatsApp.' },
        ],
      },
      {
        id: 'pharma_ordonnance_wa',
        name: 'Ordonnance WhatsApp & Devis',
        description: 'Le client envoie une photo d’ordonnance. L’agent extrait les produits, vérifie disponibilité, prépare un devis et réserve le panier.',
        pillar: 'communication_client',
        icon: MessageSquare,
        tags: ['Ordonnance', 'WhatsApp', 'Devis'],
        effort: 'Avancé',
        timeline: '3–5 sem',
        agent: 'Nora',
        agentAvatar: '/agents/nora-3d.png',
        metrics: [{ label: 'Devis auto', value: '90%' }, { label: 'Temps comptoir', value: '-40%' }],
        prospectScript: [
          { from: 'client', text: 'Bonsoir, je peux envoyer mon ordonnance ?' },
          { from: 'agent', text: 'Bonsoir ! Oui, envoyez la photo ici. Je vérifie les disponibilités et je vous prépare le devis.' },
          { from: 'client', text: 'Voilà.' },
          { from: 'agent', text: 'Ordonnance reçue ✅\n\n3 produits disponibles sur 4.\nTotal disponible : **18 700 FCFA**.\nLe 4e produit peut être commandé pour demain 10h. Réserver le panier ?' },
        ],
        bossScript: [
          { from: 'agent', text: '📄 **Nouvelle ordonnance traitée**\n\nClient : Mme Ngo\n3/4 produits disponibles · Panier : **18 700 FCFA**\nProduit manquant identifié et fournisseur proposé.' },
          { from: 'boss', text: 'Combien d’ordonnances cette semaine ?' },
          { from: 'agent', text: '**74 ordonnances** reçues sur WhatsApp.\n\n61 devis envoyés automatiquement, 43 convertis.\nCA généré : **812 000 FCFA**.' },
        ],
      },
      {
        id: 'pharma_delivery_refill',
        name: 'Réservation & Livraison Médicaments',
        description: 'Réservation au comptoir ou livraison à domicile avec paiement Mobile Money, statut de préparation et confirmation de retrait.',
        pillar: 'communication_client',
        icon: TruckIcon,
        tags: ['Réservation', 'Livraison', 'Paiement'],
        effort: 'Moyen',
        timeline: '2 sem',
        agent: 'Nora',
        agentAvatar: '/agents/nora-3d.png',
        metrics: [{ label: 'Paniers réservés', value: '+35%' }, { label: 'Files d’attente', value: '-30%' }],
        prospectScript: [
          { from: 'agent', text: 'Votre panier est prêt ✅\n\nMontant : **18 700 FCFA**\nRetrait comptoir ou livraison ?' },
          { from: 'client', text: 'Livraison à Bonamoussadi.' },
          { from: 'agent', text: 'Livraison possible entre **17h et 19h**. Frais : **1 000 FCFA**.\nPaiement Orange Money ou MTN Momo ?' },
        ],
        bossScript: [
          { from: 'agent', text: '🚚 **Livraisons pharmacie — aujourd’hui**\n\n18 paniers préparés · 14 livrés · 4 retraits comptoir\nCA livraison : **286 000 FCFA**.' },
          { from: 'boss', text: 'Des paniers non récupérés ?' },
          { from: 'agent', text: '2 paniers non récupérés après 2h. Relances envoyées automatiquement.\n\nSi non-réponse dans 1h, je libère le stock.' },
        ],
      },
      {
        id: 'pharma_treatment_reminders',
        name: 'Rappels Traitement & Renouvellement',
        description: 'Rappels personnalisés pour traitements chroniques : prise, fin de boîte, renouvellement ordonnance et retour en pharmacie.',
        pillar: 'fidelisation',
        icon: Bell,
        tags: ['Rappel', 'Chronique', 'Renouvellement'],
        effort: 'Moyen',
        timeline: '1–2 sem',
        agent: 'Nora',
        agentAvatar: '/agents/nora-3d.png',
        metrics: [{ label: 'Réachat', value: '+42%' }, { label: 'Observance', value: '+30%' }],
        prospectScript: [
          { from: 'agent', text: 'Bonjour M. Talla. Votre traitement tension arrive normalement à la fin dans **3 jours**.\n\nVoulez-vous réserver votre renouvellement ?' },
          { from: 'client', text: 'Oui, même médicament.' },
          { from: 'agent', text: 'Réservé ✅ Disponible aujourd’hui à partir de 15h. Je vous rappelle aussi le prochain renouvellement dans 30 jours.' },
        ],
        bossScript: [
          { from: 'agent', text: '🔁 **Renouvellements traitements — semaine**\n\n96 rappels envoyés · 41 réservations confirmées\nCA récurrent récupéré : **524 000 FCFA**.' },
          { from: 'boss', text: 'Quels profils reviennent le plus ?' },
          { from: 'agent', text: 'Traitements tension et diabète : **64% des renouvellements**.\n\nJe recommande de créer un segment suivi mensuel pour ces patients.' },
        ],
      },
      {
        id: 'pharma_loyalty_health',
        name: 'Programme Fidélité Santé',
        description: 'Segmentation des clients réguliers, offres responsables sur parapharmacie, anniversaires, conseils prévention et avis Google.',
        pillar: 'fidelisation',
        icon: Heart,
        tags: ['Fidélité', 'Prévention', 'Avis'],
        effort: 'Simple',
        timeline: '1 sem',
        agent: 'Nora',
        agentAvatar: '/agents/nora-3d.png',
        metrics: [{ label: 'Clients actifs', value: '+28%' }, { label: 'Avis Google', value: '+4.7★' }],
        prospectScript: [
          { from: 'agent', text: 'Bonjour Carine 😊 Merci pour votre visite à la Pharmacie Centrale.\n\nVotre carte santé gagne **120 points**. Vous avez maintenant droit à **-10% sur la parapharmacie**.' },
          { from: 'client', text: 'Super, merci.' },
          { from: 'agent', text: 'Avec plaisir. Je peux aussi vous envoyer nos conseils prévention du mois si vous le souhaitez.' },
        ],
        bossScript: [
          { from: 'agent', text: '💙 **Fidélité santé — ce mois**\n\n428 clients inscrits · 71 retours en pharmacie · 29 avis Google collectés.' },
          { from: 'boss', text: 'Ça rapporte vraiment ?' },
          { from: 'agent', text: 'Oui. Les clients inscrits reviennent **1,8x plus souvent**.\n\nCA additionnel estimé : **+640 000 FCFA** ce mois.' },
        ],
      },
    ],
    intents: [
      {
        id: 'pharmacy_prescription_flow',
        name: 'Ordonnance WhatsApp & Stock Médical',
        icon: Pill,
        description: 'Transformez WhatsApp en comptoir digital : ordonnance, devis, stock, réservation et renouvellement.',
        agentName: 'Nora',
        agentAvatar: '/agents/nora-3d.png',
        agentRole: 'Pharmacy Agent',
        impact: 'Ordonnances traitées sans file d’attente',
        metrics: [
          { label: 'Devis Auto', value: '90%', trend: 'up', change: '+50%' },
          { label: 'Ruptures', value: '-85%', trend: 'down', change: 'Critique' },
          { label: 'Réachat', value: '+42%', trend: 'up', change: '+18%' },
        ],
        qrData: {
          label: 'Envoyer mon ordonnance',
          description: 'QR au comptoir, sur vitrine ou carte pharmacie.',
          placeholderUrl: 'https://api.qrserver.com/v1/create-qr-code/?size=300x300&data=ozirus_pharmacy_prescription&color=0EA5E9',
        },
        valueProp: {
          title: 'Ce que gagne la pharmacie',
          points: [
            'Ordonnances WhatsApp transformées en paniers réservés',
            'Alertes stock et péremption avant perte ou rupture',
            'Rappels de renouvellement pour traitements chroniques',
          ],
          mainMetric: '+812 000 FCFA de CA WhatsApp par semaine',
        },
        schema: [
          { id: 'p1', type: 'trigger', label: 'Photo Ordonnance', sublabel: 'Client envoie WhatsApp', icon: FileText, position: { x: 10, y: 50 }, status: 'success' },
          { id: 'p2', type: 'process', label: 'Lecture IA', sublabel: 'Nora extrait les produits', icon: Bot, agent: 'Nora', position: { x: 30, y: 35 }, status: 'active' },
          { id: 'p3', type: 'action', label: 'Vérif Stock', sublabel: 'Lots et disponibilité', icon: Package, position: { x: 52, y: 20 }, status: 'success' },
          { id: 'p4', type: 'action', label: 'Devis & Paiement', sublabel: 'Mobile Money', icon: Wallet, position: { x: 52, y: 75 }, status: 'success' },
          { id: 'p5', type: 'process', label: 'Rappel Traitement', sublabel: 'Renouvellement J-3', icon: Bell, agent: 'Nora', position: { x: 75, y: 50 }, status: 'active' },
          { id: 'p6', type: 'result', label: 'Client Fidèle', sublabel: 'Retour mensuel', icon: Heart, position: { x: 95, y: 50 }, status: 'success' },
        ],
      },
    ],
  },

  // ─── ÉDUCATION ────────────────────────────────────────────────────────────
  {
    id: 'education',
    name: 'Éducation',
    icon: GraduationCap,
    color: '#8B5CF6',
    tagline: 'Admissions, scolarité, parents : une école pilotée sans chaos.',
    deliverables: [
      {
        id: 'edu_student_admin',
        name: 'Gestion Élèves & Dossiers',
        description: 'Base élèves centralisée : inscriptions, classes, contacts parents, documents, historique paiements et statut administratif.',
        pillar: 'backend_office',
        icon: Users,
        tags: ['Élèves', 'Dossiers', 'Scolarité'],
        effort: 'Avancé',
        timeline: '3–4 sem',
        agent: 'Maya',
        agentAvatar: '/agents/maya-3d.png',
        metrics: [{ label: 'Dossiers complets', value: '98%' }, { label: 'Temps admin', value: '-15h/sem' }],
        prospectScript: [
          { from: 'boss', text: 'Combien d’élèves inscrits en 6e ?' },
          { from: 'agent', text: '📚 **Classe 6e — Collège Horizon**\n\n62 élèves inscrits · 58 dossiers complets · 4 pièces manquantes.\n\nJe relance les parents concernés ?' },
          { from: 'boss', text: 'Oui.' },
          { from: 'agent', text: 'Relances envoyées aux 4 parents ✅ Liste mise à jour automatiquement.' },
        ],
        bossScript: [
          { from: 'agent', text: '📋 **État administratif — rentrée**\n\n421 élèves · 389 dossiers complets · 32 incomplets\nPièces les plus manquantes : acte de naissance, photo, reçu inscription.' },
          { from: 'boss', text: 'Avant ça prenait combien de temps ?' },
          { from: 'agent', text: 'Avant : environ **2 semaines** de vérification manuelle.\nMaintenant : suivi en temps réel et relance automatique des parents.' },
        ],
      },
      {
        id: 'edu_fee_tracking',
        name: 'Suivi Scolarité & Relances',
        description: 'Échéancier des frais, reçus automatiques, relances parents, promesses de paiement et alertes direction.',
        pillar: 'backend_office',
        icon: Receipt,
        tags: ['Scolarité', 'Paiement', 'Relances'],
        effort: 'Moyen',
        timeline: '2 sem',
        agent: 'Maya',
        agentAvatar: '/agents/maya-3d.png',
        metrics: [{ label: 'Impayés', value: '-55%' }, { label: 'Recouvrement', value: '+38%' }],
        prospectScript: [
          { from: 'agent', text: 'Bonjour Mme Essomba. Rappel : la 2e tranche de scolarité de Kevin arrive à échéance le **10 juin**.\n\nMontant restant : **85 000 FCFA**.' },
          { from: 'client', text: 'Je paie vendredi.' },
          { from: 'agent', text: 'Promesse de paiement notée pour vendredi ✅ Je vous enverrai le lien Mobile Money le matin.' },
        ],
        bossScript: [
          { from: 'agent', text: '💰 **Scolarité — point du jour**\n\n38 parents relancés · 17 promesses de paiement · 9 paiements reçus\nMontant récupéré : **1 240 000 FCFA**.' },
          { from: 'boss', text: 'Combien d’impayés critiques ?' },
          { from: 'agent', text: '12 dossiers critiques à +30 jours, total **1 870 000 FCFA**.\n\nJe propose appel humain pour 5 familles prioritaires.' },
        ],
      },
      {
        id: 'edu_admission_whatsapp',
        name: 'Admissions WhatsApp IA',
        description: 'L’agent répond aux parents, qualifie la demande, partage les frais, collecte les pièces et planifie le test d’entrée.',
        pillar: 'communication_client',
        icon: MessageSquare,
        tags: ['Admissions', 'WhatsApp', 'Qualification'],
        effort: 'Avancé',
        timeline: '3–5 sem',
        agent: 'Maya',
        agentAvatar: '/agents/maya-3d.png',
        metrics: [{ label: 'Demandes traitées', value: '100%' }, { label: 'Inscriptions', value: '+32%' }],
        prospectScript: [
          { from: 'client', text: 'Bonjour, je cherche une place en 4e pour mon fils.' },
          { from: 'agent', text: 'Bonjour ! Je suis Maya du **Collège Horizon** 🎓\n\nIl reste **8 places** en 4e. Souhaitez-vous recevoir les frais, le programme et les pièces à fournir ?' },
          { from: 'client', text: 'Oui.' },
          { from: 'agent', text: 'Voici le dossier admission : frais annuels, tenue, calendrier et pièces requises.\n\nJe peux aussi réserver un test d’entrée mercredi ou samedi.' },
        ],
        bossScript: [
          { from: 'agent', text: '🎯 **Admissions — cette semaine**\n\n64 demandes WhatsApp · 41 parents qualifiés · 18 tests planifiés · 9 inscriptions confirmées.' },
          { from: 'boss', text: 'Quelle classe demande le plus ?' },
          { from: 'agent', text: 'La 6e représente **38% des demandes**, suivie de la 4e avec 21%.\n\nJe recommande une campagne ciblée parents CM2 cette semaine.' },
        ],
      },
      {
        id: 'edu_parent_communication',
        name: 'Communication Parents Automatique',
        description: 'Absences, retards, annonces, devoirs, réunions et urgences envoyés aux parents sur WhatsApp avec accusé de lecture.',
        pillar: 'communication_client',
        icon: Bell,
        tags: ['Parents', 'Absences', 'Annonces'],
        effort: 'Moyen',
        timeline: '1–2 sem',
        agent: 'Maya',
        agentAvatar: '/agents/maya-3d.png',
        metrics: [{ label: 'Appels admin', value: '-70%' }, { label: 'Parents informés', value: '96%' }],
        prospectScript: [
          { from: 'agent', text: 'Bonjour Mme Talla. Votre fille Sarah est absente ce matin en Mathématiques.\n\nMerci de confirmer si l’absence est justifiée.' },
          { from: 'client', text: 'Elle est malade, certificat demain.' },
          { from: 'agent', text: 'Noté ✅ Absence justifiée provisoirement. Vous pourrez envoyer le certificat ici.' },
        ],
        bossScript: [
          { from: 'agent', text: '📣 **Communication parents — aujourd’hui**\n\n126 messages envoyés · 114 lus · 23 réponses traitées automatiquement.' },
          { from: 'boss', text: 'Des urgences ?' },
          { from: 'agent', text: '2 absences non justifiées après 3 relances. Je les ai marquées pour appel surveillant général.' },
        ],
      },
      {
        id: 'edu_grades_reports',
        name: 'Bulletins & Suivi Performance',
        description: 'Saisie/import des notes, génération de bulletins PDF, alertes élèves à risque et recommandations de soutien.',
        pillar: 'fidelisation',
        icon: ChartBar,
        tags: ['Notes', 'Bulletins', 'Soutien'],
        effort: 'Avancé',
        timeline: '3–4 sem',
        agent: 'Maya',
        agentAvatar: '/agents/maya-3d.png',
        metrics: [{ label: 'Bulletins générés', value: '100%' }, { label: 'Élèves à risque', value: 'Détectés' }],
        prospectScript: [
          { from: 'client', text: 'Bonjour, je peux avoir les notes de Sarah ?' },
          { from: 'agent', text: 'Bonjour Mme Talla. Moyenne actuelle de Sarah : **13,8/20**.\n\nPoint fort : Français. À renforcer : Mathématiques, moyenne 9,5/20.\nUn atelier de soutien est disponible mercredi.' },
        ],
        bossScript: [
          { from: 'agent', text: '📊 **Performance trimestre 2**\n\n421 bulletins générés · 67 élèves à risque détectés · 34 recommandations de soutien envoyées aux parents.' },
          { from: 'boss', text: 'Quelle classe baisse ?' },
          { from: 'agent', text: 'La 3e B baisse de **-1,7 point** en moyenne, surtout en Maths et Physique.\n\nJe recommande un plan de soutien sur 4 semaines.' },
        ],
      },
      {
        id: 'edu_alumni_referral',
        name: 'Fidélisation Parents & Parrainage',
        description: 'Enquêtes satisfaction parents, avis Google, parrainage de nouvelles familles et réactivation des anciens élèves.',
        pillar: 'fidelisation',
        icon: Share2,
        tags: ['Parrainage', 'Avis', 'Anciens'],
        effort: 'Simple',
        timeline: '1 sem',
        agent: 'Maya',
        agentAvatar: '/agents/maya-3d.png',
        metrics: [{ label: 'Leads référés', value: '+27%' }, { label: 'Avis parents', value: '+4.8★' }],
        prospectScript: [
          { from: 'agent', text: 'Bonjour Mme Essomba 😊 Merci pour votre confiance cette année.\n\nSi vous recommandez le Collège Horizon à une famille, vous recevez **25 000 FCFA de réduction** sur la prochaine tranche.' },
          { from: 'client', text: 'Je peux partager à ma sœur ?' },
          { from: 'agent', text: 'Oui. Voici votre lien : horizon.cm/ref/essomba\nJe vous notifie si son dossier est validé.' },
        ],
        bossScript: [
          { from: 'agent', text: '🤝 **Parrainage parents — ce mois**\n\n31 liens partagés · 12 demandes reçues · 5 inscriptions confirmées.' },
          { from: 'boss', text: 'Coût acquisition ?' },
          { from: 'agent', text: 'Réductions accordées : **125 000 FCFA**.\nCA scolarité généré : **1 875 000 FCFA**.\nROI très favorable.' },
        ],
      },
    ],
    intents: [
      {
        id: 'education_admission_parent_flow',
        name: 'Admissions & Communication Parents',
        icon: GraduationCap,
        description: 'Automatisez le parcours parent : admission, dossier, scolarité, absences, notes et fidélisation.',
        agentName: 'Maya',
        agentAvatar: '/agents/maya-3d.png',
        agentRole: 'School Ops Agent',
        impact: 'Moins d’administration, plus d’inscriptions',
        metrics: [
          { label: 'Inscriptions', value: '+32%', trend: 'up', change: '+14' },
          { label: 'Impayés', value: '-55%', trend: 'down', change: '-1.8M' },
          { label: 'Parents Informés', value: '96%', trend: 'up', change: '+35%' },
        ],
        qrData: {
          label: 'Demander une admission',
          description: 'QR sur affiche, site web, WhatsApp Business et prospectus.',
          placeholderUrl: 'https://api.qrserver.com/v1/create-qr-code/?size=300x300&data=ozirus_education_admission&color=8B5CF6',
        },
        valueProp: {
          title: 'Ce que gagne l’établissement',
          points: [
            'Admissions qualifiées et tests planifiés automatiquement',
            'Relance scolarité sans conflit manuel avec les parents',
            'Communication absences, notes et annonces centralisée',
          ],
          mainMetric: '+9 inscriptions confirmées par semaine via WhatsApp',
        },
        schema: [
          { id: 'e1', type: 'trigger', label: 'Parent Contacte', sublabel: 'WhatsApp admission', icon: MessageSquare, position: { x: 10, y: 50 }, status: 'success' },
          { id: 'e2', type: 'process', label: 'Qualification IA', sublabel: 'Maya classe et budget', icon: Bot, agent: 'Maya', position: { x: 30, y: 30 }, status: 'active' },
          { id: 'e3', type: 'action', label: 'Dossier Élève', sublabel: 'Pièces collectées', icon: FileText, position: { x: 30, y: 70 }, status: 'success' },
          { id: 'e4', type: 'action', label: 'Paiement Scolarité', sublabel: 'Reçu automatique', icon: Receipt, position: { x: 58, y: 30 }, status: 'success' },
          { id: 'e5', type: 'process', label: 'Suivi Parent', sublabel: 'Absences et notes', icon: Bell, agent: 'Maya', position: { x: 58, y: 70 }, status: 'active' },
          { id: 'e6', type: 'result', label: 'Famille Fidèle', sublabel: 'Parrainage', icon: Share2, position: { x: 90, y: 50 }, status: 'success' },
        ],
      },
    ],
  },
];
